// Сгенерировано Pigeon из pigeons/messages.dart. Не редактировать вручную:
// изменения вносятся в контракт, затем выполняется `make gen`.
// Autogenerated from Pigeon (v25.5.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
  let code: String
  let message: String?
  let details: Sendable?

  init(code: String, message: String?, details: Sendable?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
  }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func createConnectionError(withChannelName channelName: String) -> PigeonError {
  return PigeonError(code: "channel-error", message: "Unable to establish connection on channel: '\(channelName)'.", details: "")
}

private func isNullish(_ value: Any?) -> Bool {
  return value is NSNull || value == nil
}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}

func deepEqualsMessages(_ lhs: Any?, _ rhs: Any?) -> Bool {
  let cleanLhs = nilOrValue(lhs) as Any?
  let cleanRhs = nilOrValue(rhs) as Any?
  switch (cleanLhs, cleanRhs) {
  case (nil, nil):
    return true

  case (nil, _), (_, nil):
    return false

  case is (Void, Void):
    return true

  case let (cleanLhsHashable, cleanRhsHashable) as (AnyHashable, AnyHashable):
    return cleanLhsHashable == cleanRhsHashable

  case let (cleanLhsArray, cleanRhsArray) as ([Any?], [Any?]):
    guard cleanLhsArray.count == cleanRhsArray.count else { return false }
    for (index, element) in cleanLhsArray.enumerated() {
      if !deepEqualsMessages(element, cleanRhsArray[index]) {
        return false
      }
    }
    return true

  case let (cleanLhsDictionary, cleanRhsDictionary) as ([AnyHashable: Any?], [AnyHashable: Any?]):
    guard cleanLhsDictionary.count == cleanRhsDictionary.count else { return false }
    for (key, cleanLhsValue) in cleanLhsDictionary {
      guard cleanRhsDictionary.index(forKey: key) != nil else { return false }
      if !deepEqualsMessages(cleanLhsValue, cleanRhsDictionary[key]!) {
        return false
      }
    }
    return true

  default:
    // Any other type shouldn't be able to be used with pigeon. File an issue if you find this to be untrue.
    return false
  }
}

func deepHashMessages(value: Any?, hasher: inout Hasher) {
  if let valueList = value as? [AnyHashable] {
     for item in valueList { deepHashMessages(value: item, hasher: &hasher) }
     return
  }

  if let valueDict = value as? [AnyHashable: AnyHashable] {
    for key in valueDict.keys { 
      hasher.combine(key)
      deepHashMessages(value: valueDict[key]!, hasher: &hasher)
    }
    return
  }

  if let hashableValue = value as? AnyHashable {
    hasher.combine(hashableValue.hashValue)
  }

  return hasher.combine(String(describing: value))
}

    

/// Готовый стиль из состава SDK.
enum PlatformPredefinedStyle: Int {
  case main = 0
  case dark = 1
  case grayLight = 2
  case simple = 3
  case simpleDark = 4
  case navigationMain = 5
  case navigationDark = 6
}

/// Каким способом задан стиль карты.
enum PlatformStyleKind: Int {
  case predefined = 0
  case json = 1
  case url = 2
}

/// Режим следования карты за индикатором пользователя.
enum PlatformMapMode: Int {
  case free = 0
  case followLocation = 1
  case followBearingAndLocation = 2
}

/// Угол, в котором показывается логотип VK.
enum PlatformLogoAlignment: Int {
  case topLeft = 0
  case topRight = 1
  case bottomLeft = 2
  case bottomRight = 3
}

/// Точка картинки маркера, стоящая на координате.
enum PlatformMarkerAlignment: Int {
  case center = 0
  case top = 1
  case bottom = 2
  case left = 3
  case right = 4
  case topLeft = 5
  case topRight = 6
  case bottomLeft = 7
  case bottomRight = 8
}

/// Кривая ускорения анимации камеры.
enum PlatformAnimationEasing: Int {
  case linear = 0
  case easeIn = 1
  case easeOut = 2
  case easeInOut = 3
}

/// Трактовка длительности анимации.
enum PlatformAnimationDurationMode: Int {
  case exact = 0
  case atMost = 1
}

/// Как карта реагирует на касание объектов стиля.
enum PlatformFeaturesSelectionMode: Int {
  case none = 0
  case handleEvents = 1
  case drawSelection = 2
  case all = 3
}

/// Способ встраивания нативной карты (учитывается только на Android).
enum PlatformViewType: Int {
  case hybrid = 0
  case virtual = 1
  case textureHybrid = 2
  case compat = 3
}

/// Чем закончилось перемещение камеры.
enum PlatformCameraAnimationResult: Int {
  case finished = 0
  case cancelled = 1
}

/// Причина перемещения камеры.
enum PlatformCameraMovingReason: Int {
  case gesture = 0
  case api = 1
  case followMode = 2
  case unknown = 3
}

/// Фаза перемещения камеры.
enum PlatformCameraMovingPhase: Int {
  case started = 0
  case moving = 1
  case singleCompleted = 2
  case allCompleted = 3
  case cancelled = 4
}

/// Тип события карты.
enum PlatformMapEventType: Int {
  case mapShown = 0
  case tap = 1
  case longTap = 2
  case markerTap = 3
  case cameraMove = 4
  case styleApplied = 5
  case modeChanged = 6
  case lowMemory = 7
  case error = 8
}

/// Generated class from Pigeon that represents data sent in messages.
struct PlatformLatLon: Hashable {
  var latitude: Double
  var longitude: Double


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> PlatformLatLon? {
    let latitude = pigeonVar_list[0] as! Double
    let longitude = pigeonVar_list[1] as! Double

    return PlatformLatLon(
      latitude: latitude,
      longitude: longitude
    )
  }
  func toList() -> [Any?] {
    return [
      latitude,
      longitude,
    ]
  }
  static func == (lhs: PlatformLatLon, rhs: PlatformLatLon) -> Bool {
    return deepEqualsMessages(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashMessages(value: toList(), hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct PlatformLatLonBounds: Hashable {
  var southwest: PlatformLatLon
  var northeast: PlatformLatLon


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> PlatformLatLonBounds? {
    let southwest = pigeonVar_list[0] as! PlatformLatLon
    let northeast = pigeonVar_list[1] as! PlatformLatLon

    return PlatformLatLonBounds(
      southwest: southwest,
      northeast: northeast
    )
  }
  func toList() -> [Any?] {
    return [
      southwest,
      northeast,
    ]
  }
  static func == (lhs: PlatformLatLonBounds, rhs: PlatformLatLonBounds) -> Bool {
    return deepEqualsMessages(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashMessages(value: toList(), hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct PlatformScreenPoint: Hashable {
  var x: Double
  var y: Double


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> PlatformScreenPoint? {
    let x = pigeonVar_list[0] as! Double
    let y = pigeonVar_list[1] as! Double

    return PlatformScreenPoint(
      x: x,
      y: y
    )
  }
  func toList() -> [Any?] {
    return [
      x,
      y,
    ]
  }
  static func == (lhs: PlatformScreenPoint, rhs: PlatformScreenPoint) -> Bool {
    return deepEqualsMessages(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashMessages(value: toList(), hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct PlatformEdgeInsets: Hashable {
  var left: Double
  var top: Double
  var right: Double
  var bottom: Double


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> PlatformEdgeInsets? {
    let left = pigeonVar_list[0] as! Double
    let top = pigeonVar_list[1] as! Double
    let right = pigeonVar_list[2] as! Double
    let bottom = pigeonVar_list[3] as! Double

    return PlatformEdgeInsets(
      left: left,
      top: top,
      right: right,
      bottom: bottom
    )
  }
  func toList() -> [Any?] {
    return [
      left,
      top,
      right,
      bottom,
    ]
  }
  static func == (lhs: PlatformEdgeInsets, rhs: PlatformEdgeInsets) -> Bool {
    return deepEqualsMessages(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashMessages(value: toList(), hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct PlatformCameraPosition: Hashable {
  var target: PlatformLatLon
  var zoom: Double
  var bearing: Double
  var pitch: Double


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> PlatformCameraPosition? {
    let target = pigeonVar_list[0] as! PlatformLatLon
    let zoom = pigeonVar_list[1] as! Double
    let bearing = pigeonVar_list[2] as! Double
    let pitch = pigeonVar_list[3] as! Double

    return PlatformCameraPosition(
      target: target,
      zoom: zoom,
      bearing: bearing,
      pitch: pitch
    )
  }
  func toList() -> [Any?] {
    return [
      target,
      zoom,
      bearing,
      pitch,
    ]
  }
  static func == (lhs: PlatformCameraPosition, rhs: PlatformCameraPosition) -> Bool {
    return deepEqualsMessages(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashMessages(value: toList(), hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct PlatformCameraOptions: Hashable {
  var zoom: Double? = nil
  var bearing: Double? = nil
  var pitch: Double? = nil
  var padding: PlatformEdgeInsets? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> PlatformCameraOptions? {
    let zoom: Double? = nilOrValue(pigeonVar_list[0])
    let bearing: Double? = nilOrValue(pigeonVar_list[1])
    let pitch: Double? = nilOrValue(pigeonVar_list[2])
    let padding: PlatformEdgeInsets? = nilOrValue(pigeonVar_list[3])

    return PlatformCameraOptions(
      zoom: zoom,
      bearing: bearing,
      pitch: pitch,
      padding: padding
    )
  }
  func toList() -> [Any?] {
    return [
      zoom,
      bearing,
      pitch,
      padding,
    ]
  }
  static func == (lhs: PlatformCameraOptions, rhs: PlatformCameraOptions) -> Bool {
    return deepEqualsMessages(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashMessages(value: toList(), hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct PlatformAnimationOptions: Hashable {
  var durationMillis: Int64
  var easing: PlatformAnimationEasing
  var durationMode: PlatformAnimationDurationMode


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> PlatformAnimationOptions? {
    let durationMillis = pigeonVar_list[0] as! Int64
    let easing = pigeonVar_list[1] as! PlatformAnimationEasing
    let durationMode = pigeonVar_list[2] as! PlatformAnimationDurationMode

    return PlatformAnimationOptions(
      durationMillis: durationMillis,
      easing: easing,
      durationMode: durationMode
    )
  }
  func toList() -> [Any?] {
    return [
      durationMillis,
      easing,
      durationMode,
    ]
  }
  static func == (lhs: PlatformAnimationOptions, rhs: PlatformAnimationOptions) -> Bool {
    return deepEqualsMessages(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashMessages(value: toList(), hasher: &hasher)
  }
}

/// Стиль карты: `kind` определяет, что лежит в остальных полях.
///
/// Generated class from Pigeon that represents data sent in messages.
struct PlatformStyle: Hashable {
  var kind: PlatformStyleKind
  var predefined: PlatformPredefinedStyle? = nil
  var json: String? = nil
  var url: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> PlatformStyle? {
    let kind = pigeonVar_list[0] as! PlatformStyleKind
    let predefined: PlatformPredefinedStyle? = nilOrValue(pigeonVar_list[1])
    let json: String? = nilOrValue(pigeonVar_list[2])
    let url: String? = nilOrValue(pigeonVar_list[3])

    return PlatformStyle(
      kind: kind,
      predefined: predefined,
      json: json,
      url: url
    )
  }
  func toList() -> [Any?] {
    return [
      kind,
      predefined,
      json,
      url,
    ]
  }
  static func == (lhs: PlatformStyle, rhs: PlatformStyle) -> Bool {
    return deepEqualsMessages(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashMessages(value: toList(), hasher: &hasher)
  }
}

/// Настройки карты. Незаданные поля означают «не менять».
///
/// Generated class from Pigeon that represents data sent in messages.
struct PlatformMapConfiguration: Hashable {
  var style: PlatformStyle? = nil
  var compassEnabled: Bool? = nil
  var zoomButtonsEnabled: Bool? = nil
  var currentLocationButtonEnabled: Bool? = nil
  var scrollGesturesEnabled: Bool? = nil
  var zoomGesturesEnabled: Bool? = nil
  var rotateGesturesEnabled: Bool? = nil
  var logoAlignment: PlatformLogoAlignment? = nil
  var logoInsets: PlatformEdgeInsets? = nil
  var logoIgnoresSafeArea: Bool? = nil
  var padding: PlatformEdgeInsets? = nil
  var featuresSelectionMode: PlatformFeaturesSelectionMode? = nil
  var minZoom: Double? = nil
  var maxZoom: Double? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> PlatformMapConfiguration? {
    let style: PlatformStyle? = nilOrValue(pigeonVar_list[0])
    let compassEnabled: Bool? = nilOrValue(pigeonVar_list[1])
    let zoomButtonsEnabled: Bool? = nilOrValue(pigeonVar_list[2])
    let currentLocationButtonEnabled: Bool? = nilOrValue(pigeonVar_list[3])
    let scrollGesturesEnabled: Bool? = nilOrValue(pigeonVar_list[4])
    let zoomGesturesEnabled: Bool? = nilOrValue(pigeonVar_list[5])
    let rotateGesturesEnabled: Bool? = nilOrValue(pigeonVar_list[6])
    let logoAlignment: PlatformLogoAlignment? = nilOrValue(pigeonVar_list[7])
    let logoInsets: PlatformEdgeInsets? = nilOrValue(pigeonVar_list[8])
    let logoIgnoresSafeArea: Bool? = nilOrValue(pigeonVar_list[9])
    let padding: PlatformEdgeInsets? = nilOrValue(pigeonVar_list[10])
    let featuresSelectionMode: PlatformFeaturesSelectionMode? = nilOrValue(pigeonVar_list[11])
    let minZoom: Double? = nilOrValue(pigeonVar_list[12])
    let maxZoom: Double? = nilOrValue(pigeonVar_list[13])

    return PlatformMapConfiguration(
      style: style,
      compassEnabled: compassEnabled,
      zoomButtonsEnabled: zoomButtonsEnabled,
      currentLocationButtonEnabled: currentLocationButtonEnabled,
      scrollGesturesEnabled: scrollGesturesEnabled,
      zoomGesturesEnabled: zoomGesturesEnabled,
      rotateGesturesEnabled: rotateGesturesEnabled,
      logoAlignment: logoAlignment,
      logoInsets: logoInsets,
      logoIgnoresSafeArea: logoIgnoresSafeArea,
      padding: padding,
      featuresSelectionMode: featuresSelectionMode,
      minZoom: minZoom,
      maxZoom: maxZoom
    )
  }
  func toList() -> [Any?] {
    return [
      style,
      compassEnabled,
      zoomButtonsEnabled,
      currentLocationButtonEnabled,
      scrollGesturesEnabled,
      zoomGesturesEnabled,
      rotateGesturesEnabled,
      logoAlignment,
      logoInsets,
      logoIgnoresSafeArea,
      padding,
      featuresSelectionMode,
      minZoom,
      maxZoom,
    ]
  }
  static func == (lhs: PlatformMapConfiguration, rhs: PlatformMapConfiguration) -> Bool {
    return deepEqualsMessages(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashMessages(value: toList(), hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct PlatformMapCreationParams: Hashable {
  var initialCameraPosition: PlatformCameraPosition
  var configuration: PlatformMapConfiguration
  var platformViewType: PlatformViewType


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> PlatformMapCreationParams? {
    let initialCameraPosition = pigeonVar_list[0] as! PlatformCameraPosition
    let configuration = pigeonVar_list[1] as! PlatformMapConfiguration
    let platformViewType = pigeonVar_list[2] as! PlatformViewType

    return PlatformMapCreationParams(
      initialCameraPosition: initialCameraPosition,
      configuration: configuration,
      platformViewType: platformViewType
    )
  }
  func toList() -> [Any?] {
    return [
      initialCameraPosition,
      configuration,
      platformViewType,
    ]
  }
  static func == (lhs: PlatformMapCreationParams, rhs: PlatformMapCreationParams) -> Bool {
    return deepEqualsMessages(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashMessages(value: toList(), hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct PlatformMarker: Hashable {
  var markerId: String
  var position: PlatformLatLon
  var imageId: String
  var alignment: PlatformMarkerAlignment
  var zIndex: Int64
  var visible: Bool


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> PlatformMarker? {
    let markerId = pigeonVar_list[0] as! String
    let position = pigeonVar_list[1] as! PlatformLatLon
    let imageId = pigeonVar_list[2] as! String
    let alignment = pigeonVar_list[3] as! PlatformMarkerAlignment
    let zIndex = pigeonVar_list[4] as! Int64
    let visible = pigeonVar_list[5] as! Bool

    return PlatformMarker(
      markerId: markerId,
      position: position,
      imageId: imageId,
      alignment: alignment,
      zIndex: zIndex,
      visible: visible
    )
  }
  func toList() -> [Any?] {
    return [
      markerId,
      position,
      imageId,
      alignment,
      zIndex,
      visible,
    ]
  }
  static func == (lhs: PlatformMarker, rhs: PlatformMarker) -> Bool {
    return deepEqualsMessages(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashMessages(value: toList(), hasher: &hasher)
  }
}

/// Дельта набора маркеров: только то, что изменилось.
///
/// Generated class from Pigeon that represents data sent in messages.
struct PlatformMarkerUpdates: Hashable {
  var toAdd: [PlatformMarker]
  var toChange: [PlatformMarker]
  var idsToRemove: [String]


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> PlatformMarkerUpdates? {
    let toAdd = pigeonVar_list[0] as! [PlatformMarker]
    let toChange = pigeonVar_list[1] as! [PlatformMarker]
    let idsToRemove = pigeonVar_list[2] as! [String]

    return PlatformMarkerUpdates(
      toAdd: toAdd,
      toChange: toChange,
      idsToRemove: idsToRemove
    )
  }
  func toList() -> [Any?] {
    return [
      toAdd,
      toChange,
      idsToRemove,
    ]
  }
  static func == (lhs: PlatformMarkerUpdates, rhs: PlatformMarkerUpdates) -> Bool {
    return deepEqualsMessages(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashMessages(value: toList(), hasher: &hasher)
  }
}

/// Событие карты. Набор заполненных полей определяется полем `type`.
///
/// Generated class from Pigeon that represents data sent in messages.
struct PlatformMapEvent: Hashable {
  var type: PlatformMapEventType
  var position: PlatformLatLon? = nil
  var screenPoint: PlatformScreenPoint? = nil
  var markerId: String? = nil
  var cameraPosition: PlatformCameraPosition? = nil
  var cameraMovingReason: PlatformCameraMovingReason? = nil
  var cameraMovingPhase: PlatformCameraMovingPhase? = nil
  var mode: PlatformMapMode? = nil
  var errorCode: String? = nil
  var errorMessage: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> PlatformMapEvent? {
    let type = pigeonVar_list[0] as! PlatformMapEventType
    let position: PlatformLatLon? = nilOrValue(pigeonVar_list[1])
    let screenPoint: PlatformScreenPoint? = nilOrValue(pigeonVar_list[2])
    let markerId: String? = nilOrValue(pigeonVar_list[3])
    let cameraPosition: PlatformCameraPosition? = nilOrValue(pigeonVar_list[4])
    let cameraMovingReason: PlatformCameraMovingReason? = nilOrValue(pigeonVar_list[5])
    let cameraMovingPhase: PlatformCameraMovingPhase? = nilOrValue(pigeonVar_list[6])
    let mode: PlatformMapMode? = nilOrValue(pigeonVar_list[7])
    let errorCode: String? = nilOrValue(pigeonVar_list[8])
    let errorMessage: String? = nilOrValue(pigeonVar_list[9])

    return PlatformMapEvent(
      type: type,
      position: position,
      screenPoint: screenPoint,
      markerId: markerId,
      cameraPosition: cameraPosition,
      cameraMovingReason: cameraMovingReason,
      cameraMovingPhase: cameraMovingPhase,
      mode: mode,
      errorCode: errorCode,
      errorMessage: errorMessage
    )
  }
  func toList() -> [Any?] {
    return [
      type,
      position,
      screenPoint,
      markerId,
      cameraPosition,
      cameraMovingReason,
      cameraMovingPhase,
      mode,
      errorCode,
      errorMessage,
    ]
  }
  static func == (lhs: PlatformMapEvent, rhs: PlatformMapEvent) -> Bool {
    return deepEqualsMessages(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashMessages(value: toList(), hasher: &hasher)
  }
}

private class MessagesPigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return PlatformPredefinedStyle(rawValue: enumResultAsInt)
      }
      return nil
    case 130:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return PlatformStyleKind(rawValue: enumResultAsInt)
      }
      return nil
    case 131:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return PlatformMapMode(rawValue: enumResultAsInt)
      }
      return nil
    case 132:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return PlatformLogoAlignment(rawValue: enumResultAsInt)
      }
      return nil
    case 133:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return PlatformMarkerAlignment(rawValue: enumResultAsInt)
      }
      return nil
    case 134:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return PlatformAnimationEasing(rawValue: enumResultAsInt)
      }
      return nil
    case 135:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return PlatformAnimationDurationMode(rawValue: enumResultAsInt)
      }
      return nil
    case 136:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return PlatformFeaturesSelectionMode(rawValue: enumResultAsInt)
      }
      return nil
    case 137:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return PlatformViewType(rawValue: enumResultAsInt)
      }
      return nil
    case 138:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return PlatformCameraAnimationResult(rawValue: enumResultAsInt)
      }
      return nil
    case 139:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return PlatformCameraMovingReason(rawValue: enumResultAsInt)
      }
      return nil
    case 140:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return PlatformCameraMovingPhase(rawValue: enumResultAsInt)
      }
      return nil
    case 141:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return PlatformMapEventType(rawValue: enumResultAsInt)
      }
      return nil
    case 142:
      return PlatformLatLon.fromList(self.readValue() as! [Any?])
    case 143:
      return PlatformLatLonBounds.fromList(self.readValue() as! [Any?])
    case 144:
      return PlatformScreenPoint.fromList(self.readValue() as! [Any?])
    case 145:
      return PlatformEdgeInsets.fromList(self.readValue() as! [Any?])
    case 146:
      return PlatformCameraPosition.fromList(self.readValue() as! [Any?])
    case 147:
      return PlatformCameraOptions.fromList(self.readValue() as! [Any?])
    case 148:
      return PlatformAnimationOptions.fromList(self.readValue() as! [Any?])
    case 149:
      return PlatformStyle.fromList(self.readValue() as! [Any?])
    case 150:
      return PlatformMapConfiguration.fromList(self.readValue() as! [Any?])
    case 151:
      return PlatformMapCreationParams.fromList(self.readValue() as! [Any?])
    case 152:
      return PlatformMarker.fromList(self.readValue() as! [Any?])
    case 153:
      return PlatformMarkerUpdates.fromList(self.readValue() as! [Any?])
    case 154:
      return PlatformMapEvent.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class MessagesPigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? PlatformPredefinedStyle {
      super.writeByte(129)
      super.writeValue(value.rawValue)
    } else if let value = value as? PlatformStyleKind {
      super.writeByte(130)
      super.writeValue(value.rawValue)
    } else if let value = value as? PlatformMapMode {
      super.writeByte(131)
      super.writeValue(value.rawValue)
    } else if let value = value as? PlatformLogoAlignment {
      super.writeByte(132)
      super.writeValue(value.rawValue)
    } else if let value = value as? PlatformMarkerAlignment {
      super.writeByte(133)
      super.writeValue(value.rawValue)
    } else if let value = value as? PlatformAnimationEasing {
      super.writeByte(134)
      super.writeValue(value.rawValue)
    } else if let value = value as? PlatformAnimationDurationMode {
      super.writeByte(135)
      super.writeValue(value.rawValue)
    } else if let value = value as? PlatformFeaturesSelectionMode {
      super.writeByte(136)
      super.writeValue(value.rawValue)
    } else if let value = value as? PlatformViewType {
      super.writeByte(137)
      super.writeValue(value.rawValue)
    } else if let value = value as? PlatformCameraAnimationResult {
      super.writeByte(138)
      super.writeValue(value.rawValue)
    } else if let value = value as? PlatformCameraMovingReason {
      super.writeByte(139)
      super.writeValue(value.rawValue)
    } else if let value = value as? PlatformCameraMovingPhase {
      super.writeByte(140)
      super.writeValue(value.rawValue)
    } else if let value = value as? PlatformMapEventType {
      super.writeByte(141)
      super.writeValue(value.rawValue)
    } else if let value = value as? PlatformLatLon {
      super.writeByte(142)
      super.writeValue(value.toList())
    } else if let value = value as? PlatformLatLonBounds {
      super.writeByte(143)
      super.writeValue(value.toList())
    } else if let value = value as? PlatformScreenPoint {
      super.writeByte(144)
      super.writeValue(value.toList())
    } else if let value = value as? PlatformEdgeInsets {
      super.writeByte(145)
      super.writeValue(value.toList())
    } else if let value = value as? PlatformCameraPosition {
      super.writeByte(146)
      super.writeValue(value.toList())
    } else if let value = value as? PlatformCameraOptions {
      super.writeByte(147)
      super.writeValue(value.toList())
    } else if let value = value as? PlatformAnimationOptions {
      super.writeByte(148)
      super.writeValue(value.toList())
    } else if let value = value as? PlatformStyle {
      super.writeByte(149)
      super.writeValue(value.toList())
    } else if let value = value as? PlatformMapConfiguration {
      super.writeByte(150)
      super.writeValue(value.toList())
    } else if let value = value as? PlatformMapCreationParams {
      super.writeByte(151)
      super.writeValue(value.toList())
    } else if let value = value as? PlatformMarker {
      super.writeByte(152)
      super.writeValue(value.toList())
    } else if let value = value as? PlatformMarkerUpdates {
      super.writeByte(153)
      super.writeValue(value.toList())
    } else if let value = value as? PlatformMapEvent {
      super.writeByte(154)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class MessagesPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return MessagesPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return MessagesPigeonCodecWriter(data: data)
  }
}

class MessagesPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = MessagesPigeonCodec(readerWriter: MessagesPigeonCodecReaderWriter())
}


/// Разовая настройка SDK на процесс: ключ доступа и параметры сети.
///
/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol VkMapsInitializerApi {
  /// Настраивает SDK. Повторный вызов с теми же параметрами ничего не делает.
  func setup(apiKey: String, baseUrl: String?, locale: String?, completion: @escaping (Result<Bool, Error>) -> Void)
  /// Настроен ли SDK.
  func isInitialized() throws -> Bool
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class VkMapsInitializerApiSetup {
  static var codec: FlutterStandardMessageCodec { MessagesPigeonCodec.shared }
  /// Sets up an instance of `VkMapsInitializerApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: VkMapsInitializerApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    /// Настраивает SDK. Повторный вызов с теми же параметрами ничего не делает.
    let setupChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.vk_maps_mapkit_platform_interface.VkMapsInitializerApi.setup\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setupChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let apiKeyArg = args[0] as! String
        let baseUrlArg: String? = nilOrValue(args[1])
        let localeArg: String? = nilOrValue(args[2])
        api.setup(apiKey: apiKeyArg, baseUrl: baseUrlArg, locale: localeArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      setupChannel.setMessageHandler(nil)
    }
    /// Настроен ли SDK.
    let isInitializedChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.vk_maps_mapkit_platform_interface.VkMapsInitializerApi.isInitialized\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      isInitializedChannel.setMessageHandler { _, reply in
        do {
          let result = try api.isInitialized()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      isInitializedChannel.setMessageHandler(nil)
    }
  }
}
/// Управление конкретной картой. Первый аргумент — идентификатор
/// platform view, потому что карт в приложении может быть несколько.
///
/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol VkMapsHostApi {
  /// Создаёт карту внутри уже размещённого нативного представления.
  ///
  /// Вызывается один раз сразу после появления platform view: параметры
  /// создания идут этим вызовом, а не через кодек представления, чтобы
  /// контракт оставался один на всё.
  func initializeView(viewId: Int64, params: PlatformMapCreationParams, completion: @escaping (Result<Void, Error>) -> Void)
  /// Применяет настройки карты. Передавать только изменившиеся поля.
  func updateConfiguration(viewId: Int64, configuration: PlatformMapConfiguration) throws
  /// Применяет дельту набора маркеров.
  func updateMarkers(viewId: Int64, updates: PlatformMarkerUpdates) throws
  /// Перемещает камеру. Пустые `animation` означают мгновенное перемещение.
  func moveCamera(viewId: Int64, target: PlatformLatLon?, options: PlatformCameraOptions?, animation: PlatformAnimationOptions?, completion: @escaping (Result<PlatformCameraAnimationResult, Error>) -> Void)
  /// Вписывает область в карту.
  func fitBounds(viewId: Int64, bounds: PlatformLatLonBounds, padding: PlatformEdgeInsets, animation: PlatformAnimationOptions?, completion: @escaping (Result<PlatformCameraAnimationResult, Error>) -> Void)
  /// Текущее положение камеры.
  func getCameraPosition(viewId: Int64) throws -> PlatformCameraPosition
  /// Границы видимой области.
  func getVisibleBounds(viewId: Int64) throws -> PlatformLatLonBounds
  /// Координата по точке на экране.
  func coordinateForScreenPoint(viewId: Int64, point: PlatformScreenPoint) throws -> PlatformLatLon?
  /// Точка на экране по координате.
  func screenPointForCoordinate(viewId: Int64, coordinate: PlatformLatLon) throws -> PlatformScreenPoint?
  /// Текущий режим следования.
  func getMode(viewId: Int64) throws -> PlatformMapMode
  /// Устанавливает режим следования.
  func setMode(viewId: Int64, mode: PlatformMapMode) throws
  /// Задаёт положение индикатора пользователя.
  func setUserLocation(viewId: Int64, coordinates: PlatformLatLon?, bearing: Double?, accuracy: Double?, visible: Bool) throws
  /// Добавляет изображение в стиль карты, чтобы на него могли ссылаться
  /// маркеры.
  func addStyleImage(viewId: Int64, imageId: String, pngBytes: FlutterStandardTypedData, scale: Double, completion: @escaping (Result<Void, Error>) -> Void)
  /// Убирает изображение из стиля.
  func removeStyleImage(viewId: Int64, imageId: String) throws
  /// Освобождает ресурсы карты.
  func dispose(viewId: Int64) throws
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class VkMapsHostApiSetup {
  static var codec: FlutterStandardMessageCodec { MessagesPigeonCodec.shared }
  /// Sets up an instance of `VkMapsHostApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: VkMapsHostApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    /// Создаёт карту внутри уже размещённого нативного представления.
    ///
    /// Вызывается один раз сразу после появления platform view: параметры
    /// создания идут этим вызовом, а не через кодек представления, чтобы
    /// контракт оставался один на всё.
    let initializeViewChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.vk_maps_mapkit_platform_interface.VkMapsHostApi.initializeView\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      initializeViewChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let viewIdArg = args[0] as! Int64
        let paramsArg = args[1] as! PlatformMapCreationParams
        api.initializeView(viewId: viewIdArg, params: paramsArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      initializeViewChannel.setMessageHandler(nil)
    }
    /// Применяет настройки карты. Передавать только изменившиеся поля.
    let updateConfigurationChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.vk_maps_mapkit_platform_interface.VkMapsHostApi.updateConfiguration\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      updateConfigurationChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let viewIdArg = args[0] as! Int64
        let configurationArg = args[1] as! PlatformMapConfiguration
        do {
          try api.updateConfiguration(viewId: viewIdArg, configuration: configurationArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      updateConfigurationChannel.setMessageHandler(nil)
    }
    /// Применяет дельту набора маркеров.
    let updateMarkersChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.vk_maps_mapkit_platform_interface.VkMapsHostApi.updateMarkers\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      updateMarkersChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let viewIdArg = args[0] as! Int64
        let updatesArg = args[1] as! PlatformMarkerUpdates
        do {
          try api.updateMarkers(viewId: viewIdArg, updates: updatesArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      updateMarkersChannel.setMessageHandler(nil)
    }
    /// Перемещает камеру. Пустые `animation` означают мгновенное перемещение.
    let moveCameraChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.vk_maps_mapkit_platform_interface.VkMapsHostApi.moveCamera\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      moveCameraChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let viewIdArg = args[0] as! Int64
        let targetArg: PlatformLatLon? = nilOrValue(args[1])
        let optionsArg: PlatformCameraOptions? = nilOrValue(args[2])
        let animationArg: PlatformAnimationOptions? = nilOrValue(args[3])
        api.moveCamera(viewId: viewIdArg, target: targetArg, options: optionsArg, animation: animationArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      moveCameraChannel.setMessageHandler(nil)
    }
    /// Вписывает область в карту.
    let fitBoundsChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.vk_maps_mapkit_platform_interface.VkMapsHostApi.fitBounds\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      fitBoundsChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let viewIdArg = args[0] as! Int64
        let boundsArg = args[1] as! PlatformLatLonBounds
        let paddingArg = args[2] as! PlatformEdgeInsets
        let animationArg: PlatformAnimationOptions? = nilOrValue(args[3])
        api.fitBounds(viewId: viewIdArg, bounds: boundsArg, padding: paddingArg, animation: animationArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      fitBoundsChannel.setMessageHandler(nil)
    }
    /// Текущее положение камеры.
    let getCameraPositionChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.vk_maps_mapkit_platform_interface.VkMapsHostApi.getCameraPosition\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getCameraPositionChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let viewIdArg = args[0] as! Int64
        do {
          let result = try api.getCameraPosition(viewId: viewIdArg)
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      getCameraPositionChannel.setMessageHandler(nil)
    }
    /// Границы видимой области.
    let getVisibleBoundsChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.vk_maps_mapkit_platform_interface.VkMapsHostApi.getVisibleBounds\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getVisibleBoundsChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let viewIdArg = args[0] as! Int64
        do {
          let result = try api.getVisibleBounds(viewId: viewIdArg)
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      getVisibleBoundsChannel.setMessageHandler(nil)
    }
    /// Координата по точке на экране.
    let coordinateForScreenPointChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.vk_maps_mapkit_platform_interface.VkMapsHostApi.coordinateForScreenPoint\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      coordinateForScreenPointChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let viewIdArg = args[0] as! Int64
        let pointArg = args[1] as! PlatformScreenPoint
        do {
          let result = try api.coordinateForScreenPoint(viewId: viewIdArg, point: pointArg)
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      coordinateForScreenPointChannel.setMessageHandler(nil)
    }
    /// Точка на экране по координате.
    let screenPointForCoordinateChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.vk_maps_mapkit_platform_interface.VkMapsHostApi.screenPointForCoordinate\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      screenPointForCoordinateChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let viewIdArg = args[0] as! Int64
        let coordinateArg = args[1] as! PlatformLatLon
        do {
          let result = try api.screenPointForCoordinate(viewId: viewIdArg, coordinate: coordinateArg)
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      screenPointForCoordinateChannel.setMessageHandler(nil)
    }
    /// Текущий режим следования.
    let getModeChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.vk_maps_mapkit_platform_interface.VkMapsHostApi.getMode\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getModeChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let viewIdArg = args[0] as! Int64
        do {
          let result = try api.getMode(viewId: viewIdArg)
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      getModeChannel.setMessageHandler(nil)
    }
    /// Устанавливает режим следования.
    let setModeChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.vk_maps_mapkit_platform_interface.VkMapsHostApi.setMode\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setModeChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let viewIdArg = args[0] as! Int64
        let modeArg = args[1] as! PlatformMapMode
        do {
          try api.setMode(viewId: viewIdArg, mode: modeArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      setModeChannel.setMessageHandler(nil)
    }
    /// Задаёт положение индикатора пользователя.
    let setUserLocationChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.vk_maps_mapkit_platform_interface.VkMapsHostApi.setUserLocation\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setUserLocationChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let viewIdArg = args[0] as! Int64
        let coordinatesArg: PlatformLatLon? = nilOrValue(args[1])
        let bearingArg: Double? = nilOrValue(args[2])
        let accuracyArg: Double? = nilOrValue(args[3])
        let visibleArg = args[4] as! Bool
        do {
          try api.setUserLocation(viewId: viewIdArg, coordinates: coordinatesArg, bearing: bearingArg, accuracy: accuracyArg, visible: visibleArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      setUserLocationChannel.setMessageHandler(nil)
    }
    /// Добавляет изображение в стиль карты, чтобы на него могли ссылаться
    /// маркеры.
    let addStyleImageChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.vk_maps_mapkit_platform_interface.VkMapsHostApi.addStyleImage\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      addStyleImageChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let viewIdArg = args[0] as! Int64
        let imageIdArg = args[1] as! String
        let pngBytesArg = args[2] as! FlutterStandardTypedData
        let scaleArg = args[3] as! Double
        api.addStyleImage(viewId: viewIdArg, imageId: imageIdArg, pngBytes: pngBytesArg, scale: scaleArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      addStyleImageChannel.setMessageHandler(nil)
    }
    /// Убирает изображение из стиля.
    let removeStyleImageChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.vk_maps_mapkit_platform_interface.VkMapsHostApi.removeStyleImage\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      removeStyleImageChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let viewIdArg = args[0] as! Int64
        let imageIdArg = args[1] as! String
        do {
          try api.removeStyleImage(viewId: viewIdArg, imageId: imageIdArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      removeStyleImageChannel.setMessageHandler(nil)
    }
    /// Освобождает ресурсы карты.
    let disposeChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.vk_maps_mapkit_platform_interface.VkMapsHostApi.dispose\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      disposeChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let viewIdArg = args[0] as! Int64
        do {
          try api.dispose(viewId: viewIdArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      disposeChannel.setMessageHandler(nil)
    }
  }
}
/// События карты, которые натив шлёт во Flutter.
///
/// Generated protocol from Pigeon that represents Flutter messages that can be called from Swift.
protocol VkMapsFlutterApiProtocol {
  /// Событие карты [viewId].
  func onEvent(viewId viewIdArg: Int64, event eventArg: PlatformMapEvent, completion: @escaping (Result<Void, PigeonError>) -> Void)
}
class VkMapsFlutterApi: VkMapsFlutterApiProtocol {
  private let binaryMessenger: FlutterBinaryMessenger
  private let messageChannelSuffix: String
  init(binaryMessenger: FlutterBinaryMessenger, messageChannelSuffix: String = "") {
    self.binaryMessenger = binaryMessenger
    self.messageChannelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
  }
  var codec: MessagesPigeonCodec {
    return MessagesPigeonCodec.shared
  }
  /// Событие карты [viewId].
  func onEvent(viewId viewIdArg: Int64, event eventArg: PlatformMapEvent, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.vk_maps_mapkit_platform_interface.VkMapsFlutterApi.onEvent\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([viewIdArg, eventArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
}
