// Сгенерировано Pigeon из pigeons/messages.dart. Не редактировать вручную:
// изменения вносятся в контракт, затем выполняется `make gen`.
// Autogenerated from Pigeon (v25.5.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: public_member_api_docs, non_constant_identifier_names, avoid_as, unused_import, unnecessary_parenthesis, prefer_null_aware_operators, omit_local_variable_types, unused_shown_name, unnecessary_import, no_leading_underscores_for_local_identifiers

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List, Uint8List;

import 'package:flutter/foundation.dart' show ReadBuffer, WriteBuffer;
import 'package:flutter/services.dart';

PlatformException _createConnectionError(String channelName) {
  return PlatformException(
    code: 'channel-error',
    message: 'Unable to establish connection on channel: "$channelName".',
  );
}

List<Object?> wrapResponse({
  Object? result,
  PlatformException? error,
  bool empty = false,
}) {
  if (empty) {
    return <Object?>[];
  }
  if (error == null) {
    return <Object?>[result];
  }
  return <Object?>[error.code, error.message, error.details];
}

bool _deepEquals(Object? a, Object? b) {
  if (a is List && b is List) {
    return a.length == b.length &&
        a.indexed.every(
          ((int, dynamic) item) => _deepEquals(item.$2, b[item.$1]),
        );
  }
  if (a is Map && b is Map) {
    return a.length == b.length &&
        a.entries.every(
          (MapEntry<Object?, Object?> entry) =>
              (b as Map<Object?, Object?>).containsKey(entry.key) &&
              _deepEquals(entry.value, b[entry.key]),
        );
  }
  return a == b;
}

/// Готовый стиль из состава SDK.
enum PlatformPredefinedStyle {
  main,
  dark,
  grayLight,
  simple,
  simpleDark,
  navigationMain,
  navigationDark,
}

/// Каким способом задан стиль карты.
enum PlatformStyleKind { predefined, json, url }

/// Режим следования карты за индикатором пользователя.
enum PlatformMapMode { free, followLocation, followBearingAndLocation }

/// Угол, в котором показывается логотип VK.
enum PlatformLogoAlignment { topLeft, topRight, bottomLeft, bottomRight }

/// Точка картинки маркера, стоящая на координате.
enum PlatformMarkerAlignment {
  center,
  top,
  bottom,
  left,
  right,
  topLeft,
  topRight,
  bottomLeft,
  bottomRight,
}

/// Кривая ускорения анимации камеры.
enum PlatformAnimationEasing { linear, easeIn, easeOut, easeInOut }

/// Трактовка длительности анимации.
enum PlatformAnimationDurationMode { exact, atMost }

/// Как карта реагирует на касание объектов стиля.
enum PlatformFeaturesSelectionMode { none, handleEvents, drawSelection, all }

/// Способ встраивания нативной карты (учитывается только на Android).
enum PlatformViewType { hybrid, virtual, textureHybrid, compat }

/// Чем закончилось перемещение камеры.
enum PlatformCameraAnimationResult { finished, cancelled }

/// Причина перемещения камеры.
enum PlatformCameraMovingReason { gesture, api, followMode, unknown }

/// Фаза перемещения камеры.
enum PlatformCameraMovingPhase {
  started,
  moving,
  singleCompleted,
  allCompleted,
  cancelled,
}

/// Тип события карты.
enum PlatformMapEventType {
  mapShown,
  tap,
  longTap,
  markerTap,
  cameraMove,
  styleApplied,
  modeChanged,
  lowMemory,
  error,
}

class PlatformLatLon {
  PlatformLatLon({required this.latitude, required this.longitude});

  double latitude;

  double longitude;

  List<Object?> _toList() {
    return <Object?>[latitude, longitude];
  }

  Object encode() {
    return _toList();
  }

  static PlatformLatLon decode(Object result) {
    result as List<Object?>;
    return PlatformLatLon(
      latitude: result[0]! as double,
      longitude: result[1]! as double,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! PlatformLatLon || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList());
}

class PlatformLatLonBounds {
  PlatformLatLonBounds({required this.southwest, required this.northeast});

  PlatformLatLon southwest;

  PlatformLatLon northeast;

  List<Object?> _toList() {
    return <Object?>[southwest, northeast];
  }

  Object encode() {
    return _toList();
  }

  static PlatformLatLonBounds decode(Object result) {
    result as List<Object?>;
    return PlatformLatLonBounds(
      southwest: result[0]! as PlatformLatLon,
      northeast: result[1]! as PlatformLatLon,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! PlatformLatLonBounds || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList());
}

class PlatformScreenPoint {
  PlatformScreenPoint({required this.x, required this.y});

  double x;

  double y;

  List<Object?> _toList() {
    return <Object?>[x, y];
  }

  Object encode() {
    return _toList();
  }

  static PlatformScreenPoint decode(Object result) {
    result as List<Object?>;
    return PlatformScreenPoint(
      x: result[0]! as double,
      y: result[1]! as double,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! PlatformScreenPoint || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList());
}

class PlatformEdgeInsets {
  PlatformEdgeInsets({
    required this.left,
    required this.top,
    required this.right,
    required this.bottom,
  });

  double left;

  double top;

  double right;

  double bottom;

  List<Object?> _toList() {
    return <Object?>[left, top, right, bottom];
  }

  Object encode() {
    return _toList();
  }

  static PlatformEdgeInsets decode(Object result) {
    result as List<Object?>;
    return PlatformEdgeInsets(
      left: result[0]! as double,
      top: result[1]! as double,
      right: result[2]! as double,
      bottom: result[3]! as double,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! PlatformEdgeInsets || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList());
}

class PlatformCameraPosition {
  PlatformCameraPosition({
    required this.target,
    required this.zoom,
    required this.bearing,
    required this.pitch,
  });

  PlatformLatLon target;

  double zoom;

  double bearing;

  double pitch;

  List<Object?> _toList() {
    return <Object?>[target, zoom, bearing, pitch];
  }

  Object encode() {
    return _toList();
  }

  static PlatformCameraPosition decode(Object result) {
    result as List<Object?>;
    return PlatformCameraPosition(
      target: result[0]! as PlatformLatLon,
      zoom: result[1]! as double,
      bearing: result[2]! as double,
      pitch: result[3]! as double,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! PlatformCameraPosition || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList());
}

class PlatformCameraOptions {
  PlatformCameraOptions({this.zoom, this.bearing, this.pitch, this.padding});

  double? zoom;

  double? bearing;

  double? pitch;

  PlatformEdgeInsets? padding;

  List<Object?> _toList() {
    return <Object?>[zoom, bearing, pitch, padding];
  }

  Object encode() {
    return _toList();
  }

  static PlatformCameraOptions decode(Object result) {
    result as List<Object?>;
    return PlatformCameraOptions(
      zoom: result[0] as double?,
      bearing: result[1] as double?,
      pitch: result[2] as double?,
      padding: result[3] as PlatformEdgeInsets?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! PlatformCameraOptions || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList());
}

class PlatformAnimationOptions {
  PlatformAnimationOptions({
    required this.durationMillis,
    required this.easing,
    required this.durationMode,
  });

  int durationMillis;

  PlatformAnimationEasing easing;

  PlatformAnimationDurationMode durationMode;

  List<Object?> _toList() {
    return <Object?>[durationMillis, easing, durationMode];
  }

  Object encode() {
    return _toList();
  }

  static PlatformAnimationOptions decode(Object result) {
    result as List<Object?>;
    return PlatformAnimationOptions(
      durationMillis: result[0]! as int,
      easing: result[1]! as PlatformAnimationEasing,
      durationMode: result[2]! as PlatformAnimationDurationMode,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! PlatformAnimationOptions ||
        other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList());
}

/// Стиль карты: `kind` определяет, что лежит в остальных полях.
class PlatformStyle {
  PlatformStyle({required this.kind, this.predefined, this.json, this.url});

  PlatformStyleKind kind;

  PlatformPredefinedStyle? predefined;

  String? json;

  String? url;

  List<Object?> _toList() {
    return <Object?>[kind, predefined, json, url];
  }

  Object encode() {
    return _toList();
  }

  static PlatformStyle decode(Object result) {
    result as List<Object?>;
    return PlatformStyle(
      kind: result[0]! as PlatformStyleKind,
      predefined: result[1] as PlatformPredefinedStyle?,
      json: result[2] as String?,
      url: result[3] as String?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! PlatformStyle || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList());
}

/// Настройки карты. Незаданные поля означают «не менять».
class PlatformMapConfiguration {
  PlatformMapConfiguration({
    this.style,
    this.compassEnabled,
    this.zoomButtonsEnabled,
    this.currentLocationButtonEnabled,
    this.scrollGesturesEnabled,
    this.zoomGesturesEnabled,
    this.rotateGesturesEnabled,
    this.logoAlignment,
    this.logoInsets,
    this.logoIgnoresSafeArea,
    this.padding,
    this.featuresSelectionMode,
    this.minZoom,
    this.maxZoom,
  });

  PlatformStyle? style;

  bool? compassEnabled;

  bool? zoomButtonsEnabled;

  bool? currentLocationButtonEnabled;

  bool? scrollGesturesEnabled;

  bool? zoomGesturesEnabled;

  bool? rotateGesturesEnabled;

  PlatformLogoAlignment? logoAlignment;

  PlatformEdgeInsets? logoInsets;

  bool? logoIgnoresSafeArea;

  PlatformEdgeInsets? padding;

  PlatformFeaturesSelectionMode? featuresSelectionMode;

  double? minZoom;

  double? maxZoom;

  List<Object?> _toList() {
    return <Object?>[
      style,
      compassEnabled,
      zoomButtonsEnabled,
      currentLocationButtonEnabled,
      scrollGesturesEnabled,
      zoomGesturesEnabled,
      rotateGesturesEnabled,
      logoAlignment,
      logoInsets,
      logoIgnoresSafeArea,
      padding,
      featuresSelectionMode,
      minZoom,
      maxZoom,
    ];
  }

  Object encode() {
    return _toList();
  }

  static PlatformMapConfiguration decode(Object result) {
    result as List<Object?>;
    return PlatformMapConfiguration(
      style: result[0] as PlatformStyle?,
      compassEnabled: result[1] as bool?,
      zoomButtonsEnabled: result[2] as bool?,
      currentLocationButtonEnabled: result[3] as bool?,
      scrollGesturesEnabled: result[4] as bool?,
      zoomGesturesEnabled: result[5] as bool?,
      rotateGesturesEnabled: result[6] as bool?,
      logoAlignment: result[7] as PlatformLogoAlignment?,
      logoInsets: result[8] as PlatformEdgeInsets?,
      logoIgnoresSafeArea: result[9] as bool?,
      padding: result[10] as PlatformEdgeInsets?,
      featuresSelectionMode: result[11] as PlatformFeaturesSelectionMode?,
      minZoom: result[12] as double?,
      maxZoom: result[13] as double?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! PlatformMapConfiguration ||
        other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList());
}

class PlatformMapCreationParams {
  PlatformMapCreationParams({
    required this.initialCameraPosition,
    required this.configuration,
    required this.platformViewType,
  });

  PlatformCameraPosition initialCameraPosition;

  PlatformMapConfiguration configuration;

  PlatformViewType platformViewType;

  List<Object?> _toList() {
    return <Object?>[initialCameraPosition, configuration, platformViewType];
  }

  Object encode() {
    return _toList();
  }

  static PlatformMapCreationParams decode(Object result) {
    result as List<Object?>;
    return PlatformMapCreationParams(
      initialCameraPosition: result[0]! as PlatformCameraPosition,
      configuration: result[1]! as PlatformMapConfiguration,
      platformViewType: result[2]! as PlatformViewType,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! PlatformMapCreationParams ||
        other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList());
}

class PlatformMarker {
  PlatformMarker({
    required this.markerId,
    required this.position,
    required this.imageId,
    required this.alignment,
    required this.zIndex,
    required this.visible,
  });

  String markerId;

  PlatformLatLon position;

  String imageId;

  PlatformMarkerAlignment alignment;

  int zIndex;

  bool visible;

  List<Object?> _toList() {
    return <Object?>[markerId, position, imageId, alignment, zIndex, visible];
  }

  Object encode() {
    return _toList();
  }

  static PlatformMarker decode(Object result) {
    result as List<Object?>;
    return PlatformMarker(
      markerId: result[0]! as String,
      position: result[1]! as PlatformLatLon,
      imageId: result[2]! as String,
      alignment: result[3]! as PlatformMarkerAlignment,
      zIndex: result[4]! as int,
      visible: result[5]! as bool,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! PlatformMarker || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList());
}

/// Дельта набора маркеров: только то, что изменилось.
class PlatformMarkerUpdates {
  PlatformMarkerUpdates({
    required this.toAdd,
    required this.toChange,
    required this.idsToRemove,
  });

  List<PlatformMarker> toAdd;

  List<PlatformMarker> toChange;

  List<String> idsToRemove;

  List<Object?> _toList() {
    return <Object?>[toAdd, toChange, idsToRemove];
  }

  Object encode() {
    return _toList();
  }

  static PlatformMarkerUpdates decode(Object result) {
    result as List<Object?>;
    return PlatformMarkerUpdates(
      toAdd: (result[0] as List<Object?>?)!.cast<PlatformMarker>(),
      toChange: (result[1] as List<Object?>?)!.cast<PlatformMarker>(),
      idsToRemove: (result[2] as List<Object?>?)!.cast<String>(),
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! PlatformMarkerUpdates || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList());
}

/// Событие карты. Набор заполненных полей определяется полем `type`.
class PlatformMapEvent {
  PlatformMapEvent({
    required this.type,
    this.position,
    this.screenPoint,
    this.markerId,
    this.cameraPosition,
    this.cameraMovingReason,
    this.cameraMovingPhase,
    this.mode,
    this.errorCode,
    this.errorMessage,
  });

  PlatformMapEventType type;

  PlatformLatLon? position;

  PlatformScreenPoint? screenPoint;

  String? markerId;

  PlatformCameraPosition? cameraPosition;

  PlatformCameraMovingReason? cameraMovingReason;

  PlatformCameraMovingPhase? cameraMovingPhase;

  PlatformMapMode? mode;

  String? errorCode;

  String? errorMessage;

  List<Object?> _toList() {
    return <Object?>[
      type,
      position,
      screenPoint,
      markerId,
      cameraPosition,
      cameraMovingReason,
      cameraMovingPhase,
      mode,
      errorCode,
      errorMessage,
    ];
  }

  Object encode() {
    return _toList();
  }

  static PlatformMapEvent decode(Object result) {
    result as List<Object?>;
    return PlatformMapEvent(
      type: result[0]! as PlatformMapEventType,
      position: result[1] as PlatformLatLon?,
      screenPoint: result[2] as PlatformScreenPoint?,
      markerId: result[3] as String?,
      cameraPosition: result[4] as PlatformCameraPosition?,
      cameraMovingReason: result[5] as PlatformCameraMovingReason?,
      cameraMovingPhase: result[6] as PlatformCameraMovingPhase?,
      mode: result[7] as PlatformMapMode?,
      errorCode: result[8] as String?,
      errorMessage: result[9] as String?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! PlatformMapEvent || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList());
}

class _PigeonCodec extends StandardMessageCodec {
  const _PigeonCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is int) {
      buffer.putUint8(4);
      buffer.putInt64(value);
    } else if (value is PlatformPredefinedStyle) {
      buffer.putUint8(129);
      writeValue(buffer, value.index);
    } else if (value is PlatformStyleKind) {
      buffer.putUint8(130);
      writeValue(buffer, value.index);
    } else if (value is PlatformMapMode) {
      buffer.putUint8(131);
      writeValue(buffer, value.index);
    } else if (value is PlatformLogoAlignment) {
      buffer.putUint8(132);
      writeValue(buffer, value.index);
    } else if (value is PlatformMarkerAlignment) {
      buffer.putUint8(133);
      writeValue(buffer, value.index);
    } else if (value is PlatformAnimationEasing) {
      buffer.putUint8(134);
      writeValue(buffer, value.index);
    } else if (value is PlatformAnimationDurationMode) {
      buffer.putUint8(135);
      writeValue(buffer, value.index);
    } else if (value is PlatformFeaturesSelectionMode) {
      buffer.putUint8(136);
      writeValue(buffer, value.index);
    } else if (value is PlatformViewType) {
      buffer.putUint8(137);
      writeValue(buffer, value.index);
    } else if (value is PlatformCameraAnimationResult) {
      buffer.putUint8(138);
      writeValue(buffer, value.index);
    } else if (value is PlatformCameraMovingReason) {
      buffer.putUint8(139);
      writeValue(buffer, value.index);
    } else if (value is PlatformCameraMovingPhase) {
      buffer.putUint8(140);
      writeValue(buffer, value.index);
    } else if (value is PlatformMapEventType) {
      buffer.putUint8(141);
      writeValue(buffer, value.index);
    } else if (value is PlatformLatLon) {
      buffer.putUint8(142);
      writeValue(buffer, value.encode());
    } else if (value is PlatformLatLonBounds) {
      buffer.putUint8(143);
      writeValue(buffer, value.encode());
    } else if (value is PlatformScreenPoint) {
      buffer.putUint8(144);
      writeValue(buffer, value.encode());
    } else if (value is PlatformEdgeInsets) {
      buffer.putUint8(145);
      writeValue(buffer, value.encode());
    } else if (value is PlatformCameraPosition) {
      buffer.putUint8(146);
      writeValue(buffer, value.encode());
    } else if (value is PlatformCameraOptions) {
      buffer.putUint8(147);
      writeValue(buffer, value.encode());
    } else if (value is PlatformAnimationOptions) {
      buffer.putUint8(148);
      writeValue(buffer, value.encode());
    } else if (value is PlatformStyle) {
      buffer.putUint8(149);
      writeValue(buffer, value.encode());
    } else if (value is PlatformMapConfiguration) {
      buffer.putUint8(150);
      writeValue(buffer, value.encode());
    } else if (value is PlatformMapCreationParams) {
      buffer.putUint8(151);
      writeValue(buffer, value.encode());
    } else if (value is PlatformMarker) {
      buffer.putUint8(152);
      writeValue(buffer, value.encode());
    } else if (value is PlatformMarkerUpdates) {
      buffer.putUint8(153);
      writeValue(buffer, value.encode());
    } else if (value is PlatformMapEvent) {
      buffer.putUint8(154);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 129:
        final int? value = readValue(buffer) as int?;
        return value == null ? null : PlatformPredefinedStyle.values[value];
      case 130:
        final int? value = readValue(buffer) as int?;
        return value == null ? null : PlatformStyleKind.values[value];
      case 131:
        final int? value = readValue(buffer) as int?;
        return value == null ? null : PlatformMapMode.values[value];
      case 132:
        final int? value = readValue(buffer) as int?;
        return value == null ? null : PlatformLogoAlignment.values[value];
      case 133:
        final int? value = readValue(buffer) as int?;
        return value == null ? null : PlatformMarkerAlignment.values[value];
      case 134:
        final int? value = readValue(buffer) as int?;
        return value == null ? null : PlatformAnimationEasing.values[value];
      case 135:
        final int? value = readValue(buffer) as int?;
        return value == null
            ? null
            : PlatformAnimationDurationMode.values[value];
      case 136:
        final int? value = readValue(buffer) as int?;
        return value == null
            ? null
            : PlatformFeaturesSelectionMode.values[value];
      case 137:
        final int? value = readValue(buffer) as int?;
        return value == null ? null : PlatformViewType.values[value];
      case 138:
        final int? value = readValue(buffer) as int?;
        return value == null
            ? null
            : PlatformCameraAnimationResult.values[value];
      case 139:
        final int? value = readValue(buffer) as int?;
        return value == null ? null : PlatformCameraMovingReason.values[value];
      case 140:
        final int? value = readValue(buffer) as int?;
        return value == null ? null : PlatformCameraMovingPhase.values[value];
      case 141:
        final int? value = readValue(buffer) as int?;
        return value == null ? null : PlatformMapEventType.values[value];
      case 142:
        return PlatformLatLon.decode(readValue(buffer)!);
      case 143:
        return PlatformLatLonBounds.decode(readValue(buffer)!);
      case 144:
        return PlatformScreenPoint.decode(readValue(buffer)!);
      case 145:
        return PlatformEdgeInsets.decode(readValue(buffer)!);
      case 146:
        return PlatformCameraPosition.decode(readValue(buffer)!);
      case 147:
        return PlatformCameraOptions.decode(readValue(buffer)!);
      case 148:
        return PlatformAnimationOptions.decode(readValue(buffer)!);
      case 149:
        return PlatformStyle.decode(readValue(buffer)!);
      case 150:
        return PlatformMapConfiguration.decode(readValue(buffer)!);
      case 151:
        return PlatformMapCreationParams.decode(readValue(buffer)!);
      case 152:
        return PlatformMarker.decode(readValue(buffer)!);
      case 153:
        return PlatformMarkerUpdates.decode(readValue(buffer)!);
      case 154:
        return PlatformMapEvent.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

/// Разовая настройка SDK на процесс: ключ доступа и параметры сети.
class VkMapsInitializerApi {
  /// Constructor for [VkMapsInitializerApi].  The [binaryMessenger] named argument is
  /// available for dependency injection.  If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  VkMapsInitializerApi({
    BinaryMessenger? binaryMessenger,
    String messageChannelSuffix = '',
  }) : pigeonVar_binaryMessenger = binaryMessenger,
       pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty
           ? '.$messageChannelSuffix'
           : '';
  final BinaryMessenger? pigeonVar_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  /// Настраивает SDK. Повторный вызов с теми же параметрами ничего не делает.
  Future<bool> setup(String apiKey, String? baseUrl, String? locale) async {
    final String pigeonVar_channelName =
        'dev.flutter.pigeon.vk_maps_mapkit_platform_interface.VkMapsInitializerApi.setup$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel =
        BasicMessageChannel<Object?>(
          pigeonVar_channelName,
          pigeonChannelCodec,
          binaryMessenger: pigeonVar_binaryMessenger,
        );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[apiKey, baseUrl, locale],
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as bool?)!;
    }
  }

  /// Настроен ли SDK.
  Future<bool> isInitialized() async {
    final String pigeonVar_channelName =
        'dev.flutter.pigeon.vk_maps_mapkit_platform_interface.VkMapsInitializerApi.isInitialized$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel =
        BasicMessageChannel<Object?>(
          pigeonVar_channelName,
          pigeonChannelCodec,
          binaryMessenger: pigeonVar_binaryMessenger,
        );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as bool?)!;
    }
  }
}

/// Управление конкретной картой. Первый аргумент — идентификатор
/// platform view, потому что карт в приложении может быть несколько.
class VkMapsHostApi {
  /// Constructor for [VkMapsHostApi].  The [binaryMessenger] named argument is
  /// available for dependency injection.  If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  VkMapsHostApi({
    BinaryMessenger? binaryMessenger,
    String messageChannelSuffix = '',
  }) : pigeonVar_binaryMessenger = binaryMessenger,
       pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty
           ? '.$messageChannelSuffix'
           : '';
  final BinaryMessenger? pigeonVar_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  /// Создаёт карту внутри уже размещённого нативного представления.
  ///
  /// Вызывается один раз сразу после появления platform view: параметры
  /// создания идут этим вызовом, а не через кодек представления, чтобы
  /// контракт оставался один на всё.
  Future<void> initializeView(
    int viewId,
    PlatformMapCreationParams params,
  ) async {
    final String pigeonVar_channelName =
        'dev.flutter.pigeon.vk_maps_mapkit_platform_interface.VkMapsHostApi.initializeView$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel =
        BasicMessageChannel<Object?>(
          pigeonVar_channelName,
          pigeonChannelCodec,
          binaryMessenger: pigeonVar_binaryMessenger,
        );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[viewId, params],
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  /// Применяет настройки карты. Передавать только изменившиеся поля.
  Future<void> updateConfiguration(
    int viewId,
    PlatformMapConfiguration configuration,
  ) async {
    final String pigeonVar_channelName =
        'dev.flutter.pigeon.vk_maps_mapkit_platform_interface.VkMapsHostApi.updateConfiguration$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel =
        BasicMessageChannel<Object?>(
          pigeonVar_channelName,
          pigeonChannelCodec,
          binaryMessenger: pigeonVar_binaryMessenger,
        );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[viewId, configuration],
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  /// Применяет дельту набора маркеров.
  Future<void> updateMarkers(int viewId, PlatformMarkerUpdates updates) async {
    final String pigeonVar_channelName =
        'dev.flutter.pigeon.vk_maps_mapkit_platform_interface.VkMapsHostApi.updateMarkers$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel =
        BasicMessageChannel<Object?>(
          pigeonVar_channelName,
          pigeonChannelCodec,
          binaryMessenger: pigeonVar_binaryMessenger,
        );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[viewId, updates],
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  /// Перемещает камеру. Пустые `animation` означают мгновенное перемещение.
  Future<PlatformCameraAnimationResult> moveCamera(
    int viewId,
    PlatformLatLon? target,
    PlatformCameraOptions? options,
    PlatformAnimationOptions? animation,
  ) async {
    final String pigeonVar_channelName =
        'dev.flutter.pigeon.vk_maps_mapkit_platform_interface.VkMapsHostApi.moveCamera$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel =
        BasicMessageChannel<Object?>(
          pigeonVar_channelName,
          pigeonChannelCodec,
          binaryMessenger: pigeonVar_binaryMessenger,
        );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[viewId, target, options, animation],
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as PlatformCameraAnimationResult?)!;
    }
  }

  /// Вписывает область в карту.
  Future<PlatformCameraAnimationResult> fitBounds(
    int viewId,
    PlatformLatLonBounds bounds,
    PlatformEdgeInsets padding,
    PlatformAnimationOptions? animation,
  ) async {
    final String pigeonVar_channelName =
        'dev.flutter.pigeon.vk_maps_mapkit_platform_interface.VkMapsHostApi.fitBounds$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel =
        BasicMessageChannel<Object?>(
          pigeonVar_channelName,
          pigeonChannelCodec,
          binaryMessenger: pigeonVar_binaryMessenger,
        );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[viewId, bounds, padding, animation],
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as PlatformCameraAnimationResult?)!;
    }
  }

  /// Текущее положение камеры.
  Future<PlatformCameraPosition> getCameraPosition(int viewId) async {
    final String pigeonVar_channelName =
        'dev.flutter.pigeon.vk_maps_mapkit_platform_interface.VkMapsHostApi.getCameraPosition$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel =
        BasicMessageChannel<Object?>(
          pigeonVar_channelName,
          pigeonChannelCodec,
          binaryMessenger: pigeonVar_binaryMessenger,
        );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[viewId],
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as PlatformCameraPosition?)!;
    }
  }

  /// Границы видимой области.
  Future<PlatformLatLonBounds> getVisibleBounds(int viewId) async {
    final String pigeonVar_channelName =
        'dev.flutter.pigeon.vk_maps_mapkit_platform_interface.VkMapsHostApi.getVisibleBounds$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel =
        BasicMessageChannel<Object?>(
          pigeonVar_channelName,
          pigeonChannelCodec,
          binaryMessenger: pigeonVar_binaryMessenger,
        );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[viewId],
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as PlatformLatLonBounds?)!;
    }
  }

  /// Координата по точке на экране.
  Future<PlatformLatLon?> coordinateForScreenPoint(
    int viewId,
    PlatformScreenPoint point,
  ) async {
    final String pigeonVar_channelName =
        'dev.flutter.pigeon.vk_maps_mapkit_platform_interface.VkMapsHostApi.coordinateForScreenPoint$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel =
        BasicMessageChannel<Object?>(
          pigeonVar_channelName,
          pigeonChannelCodec,
          binaryMessenger: pigeonVar_binaryMessenger,
        );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[viewId, point],
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return (pigeonVar_replyList[0] as PlatformLatLon?);
    }
  }

  /// Точка на экране по координате.
  Future<PlatformScreenPoint?> screenPointForCoordinate(
    int viewId,
    PlatformLatLon coordinate,
  ) async {
    final String pigeonVar_channelName =
        'dev.flutter.pigeon.vk_maps_mapkit_platform_interface.VkMapsHostApi.screenPointForCoordinate$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel =
        BasicMessageChannel<Object?>(
          pigeonVar_channelName,
          pigeonChannelCodec,
          binaryMessenger: pigeonVar_binaryMessenger,
        );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[viewId, coordinate],
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return (pigeonVar_replyList[0] as PlatformScreenPoint?);
    }
  }

  /// Текущий режим следования.
  Future<PlatformMapMode> getMode(int viewId) async {
    final String pigeonVar_channelName =
        'dev.flutter.pigeon.vk_maps_mapkit_platform_interface.VkMapsHostApi.getMode$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel =
        BasicMessageChannel<Object?>(
          pigeonVar_channelName,
          pigeonChannelCodec,
          binaryMessenger: pigeonVar_binaryMessenger,
        );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[viewId],
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as PlatformMapMode?)!;
    }
  }

  /// Устанавливает режим следования.
  Future<void> setMode(int viewId, PlatformMapMode mode) async {
    final String pigeonVar_channelName =
        'dev.flutter.pigeon.vk_maps_mapkit_platform_interface.VkMapsHostApi.setMode$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel =
        BasicMessageChannel<Object?>(
          pigeonVar_channelName,
          pigeonChannelCodec,
          binaryMessenger: pigeonVar_binaryMessenger,
        );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[viewId, mode],
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  /// Задаёт положение индикатора пользователя.
  Future<void> setUserLocation(
    int viewId,
    PlatformLatLon? coordinates,
    double? bearing,
    double? accuracy,
    bool visible,
  ) async {
    final String pigeonVar_channelName =
        'dev.flutter.pigeon.vk_maps_mapkit_platform_interface.VkMapsHostApi.setUserLocation$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel =
        BasicMessageChannel<Object?>(
          pigeonVar_channelName,
          pigeonChannelCodec,
          binaryMessenger: pigeonVar_binaryMessenger,
        );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[viewId, coordinates, bearing, accuracy, visible],
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  /// Добавляет изображение в стиль карты, чтобы на него могли ссылаться
  /// маркеры.
  Future<void> addStyleImage(
    int viewId,
    String imageId,
    Uint8List pngBytes,
    double scale,
  ) async {
    final String pigeonVar_channelName =
        'dev.flutter.pigeon.vk_maps_mapkit_platform_interface.VkMapsHostApi.addStyleImage$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel =
        BasicMessageChannel<Object?>(
          pigeonVar_channelName,
          pigeonChannelCodec,
          binaryMessenger: pigeonVar_binaryMessenger,
        );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[viewId, imageId, pngBytes, scale],
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  /// Убирает изображение из стиля.
  Future<void> removeStyleImage(int viewId, String imageId) async {
    final String pigeonVar_channelName =
        'dev.flutter.pigeon.vk_maps_mapkit_platform_interface.VkMapsHostApi.removeStyleImage$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel =
        BasicMessageChannel<Object?>(
          pigeonVar_channelName,
          pigeonChannelCodec,
          binaryMessenger: pigeonVar_binaryMessenger,
        );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[viewId, imageId],
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  /// Освобождает ресурсы карты.
  Future<void> dispose(int viewId) async {
    final String pigeonVar_channelName =
        'dev.flutter.pigeon.vk_maps_mapkit_platform_interface.VkMapsHostApi.dispose$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel =
        BasicMessageChannel<Object?>(
          pigeonVar_channelName,
          pigeonChannelCodec,
          binaryMessenger: pigeonVar_binaryMessenger,
        );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[viewId],
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }
}

/// События карты, которые натив шлёт во Flutter.
abstract class VkMapsFlutterApi {
  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  /// Событие карты [viewId].
  void onEvent(int viewId, PlatformMapEvent event);

  static void setUp(
    VkMapsFlutterApi? api, {
    BinaryMessenger? binaryMessenger,
    String messageChannelSuffix = '',
  }) {
    messageChannelSuffix = messageChannelSuffix.isNotEmpty
        ? '.$messageChannelSuffix'
        : '';
    {
      final BasicMessageChannel<Object?>
      pigeonVar_channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.vk_maps_mapkit_platform_interface.VkMapsFlutterApi.onEvent$messageChannelSuffix',
        pigeonChannelCodec,
        binaryMessenger: binaryMessenger,
      );
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          assert(
            message != null,
            'Argument for dev.flutter.pigeon.vk_maps_mapkit_platform_interface.VkMapsFlutterApi.onEvent was null.',
          );
          final List<Object?> args = (message as List<Object?>?)!;
          final int? arg_viewId = (args[0] as int?);
          assert(
            arg_viewId != null,
            'Argument for dev.flutter.pigeon.vk_maps_mapkit_platform_interface.VkMapsFlutterApi.onEvent was null, expected non-null int.',
          );
          final PlatformMapEvent? arg_event = (args[1] as PlatformMapEvent?);
          assert(
            arg_event != null,
            'Argument for dev.flutter.pigeon.vk_maps_mapkit_platform_interface.VkMapsFlutterApi.onEvent was null, expected non-null PlatformMapEvent.',
          );
          try {
            api.onEvent(arg_viewId!, arg_event!);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          } catch (e) {
            return wrapResponse(
              error: PlatformException(code: 'error', message: e.toString()),
            );
          }
        });
      }
    }
  }
}
