// Сгенерировано Pigeon из pigeons/messages.dart. Не редактировать вручную:
// изменения вносятся в контракт, затем выполняется `make gen`.
// Autogenerated from Pigeon (v25.5.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package com.vk.maps.vk_maps_mapkit_android

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer
private object MessagesPigeonUtils {

  fun createConnectionError(channelName: String): FlutterError {
    return FlutterError("channel-error",  "Unable to establish connection on channel: '$channelName'.", "")  }

  fun wrapResult(result: Any?): List<Any?> {
    return listOf(result)
  }

  fun wrapError(exception: Throwable): List<Any?> {
    return if (exception is FlutterError) {
      listOf(
        exception.code,
        exception.message,
        exception.details
      )
    } else {
      listOf(
        exception.javaClass.simpleName,
        exception.toString(),
        "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
      )
    }
  }
  fun deepEquals(a: Any?, b: Any?): Boolean {
    if (a is ByteArray && b is ByteArray) {
        return a.contentEquals(b)
    }
    if (a is IntArray && b is IntArray) {
        return a.contentEquals(b)
    }
    if (a is LongArray && b is LongArray) {
        return a.contentEquals(b)
    }
    if (a is DoubleArray && b is DoubleArray) {
        return a.contentEquals(b)
    }
    if (a is Array<*> && b is Array<*>) {
      return a.size == b.size &&
          a.indices.all{ deepEquals(a[it], b[it]) }
    }
    if (a is List<*> && b is List<*>) {
      return a.size == b.size &&
          a.indices.all{ deepEquals(a[it], b[it]) }
    }
    if (a is Map<*, *> && b is Map<*, *>) {
      return a.size == b.size && a.all {
          (b as Map<Any?, Any?>).containsKey(it.key) &&
          deepEquals(it.value, b[it.key])
      }
    }
    return a == b
  }
      
}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : Throwable()

/** Готовый стиль из состава SDK. */
enum class PlatformPredefinedStyle(val raw: Int) {
  MAIN(0),
  DARK(1),
  GRAY_LIGHT(2),
  SIMPLE(3),
  SIMPLE_DARK(4),
  NAVIGATION_MAIN(5),
  NAVIGATION_DARK(6);

  companion object {
    fun ofRaw(raw: Int): PlatformPredefinedStyle? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/** Каким способом задан стиль карты. */
enum class PlatformStyleKind(val raw: Int) {
  PREDEFINED(0),
  JSON(1),
  URL(2);

  companion object {
    fun ofRaw(raw: Int): PlatformStyleKind? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/** Режим следования карты за индикатором пользователя. */
enum class PlatformMapMode(val raw: Int) {
  FREE(0),
  FOLLOW_LOCATION(1),
  FOLLOW_BEARING_AND_LOCATION(2);

  companion object {
    fun ofRaw(raw: Int): PlatformMapMode? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/** Угол, в котором показывается логотип VK. */
enum class PlatformLogoAlignment(val raw: Int) {
  TOP_LEFT(0),
  TOP_RIGHT(1),
  BOTTOM_LEFT(2),
  BOTTOM_RIGHT(3);

  companion object {
    fun ofRaw(raw: Int): PlatformLogoAlignment? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/** Точка картинки маркера, стоящая на координате. */
enum class PlatformMarkerAlignment(val raw: Int) {
  CENTER(0),
  TOP(1),
  BOTTOM(2),
  LEFT(3),
  RIGHT(4),
  TOP_LEFT(5),
  TOP_RIGHT(6),
  BOTTOM_LEFT(7),
  BOTTOM_RIGHT(8);

  companion object {
    fun ofRaw(raw: Int): PlatformMarkerAlignment? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/** Кривая ускорения анимации камеры. */
enum class PlatformAnimationEasing(val raw: Int) {
  LINEAR(0),
  EASE_IN(1),
  EASE_OUT(2),
  EASE_IN_OUT(3);

  companion object {
    fun ofRaw(raw: Int): PlatformAnimationEasing? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/** Трактовка длительности анимации. */
enum class PlatformAnimationDurationMode(val raw: Int) {
  EXACT(0),
  AT_MOST(1);

  companion object {
    fun ofRaw(raw: Int): PlatformAnimationDurationMode? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/** Как карта реагирует на касание объектов стиля. */
enum class PlatformFeaturesSelectionMode(val raw: Int) {
  NONE(0),
  HANDLE_EVENTS(1),
  DRAW_SELECTION(2),
  ALL(3);

  companion object {
    fun ofRaw(raw: Int): PlatformFeaturesSelectionMode? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/** Способ встраивания нативной карты (учитывается только на Android). */
enum class PlatformViewType(val raw: Int) {
  HYBRID(0),
  VIRTUAL(1),
  TEXTURE_HYBRID(2),
  COMPAT(3);

  companion object {
    fun ofRaw(raw: Int): PlatformViewType? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/** Чем закончилось перемещение камеры. */
enum class PlatformCameraAnimationResult(val raw: Int) {
  FINISHED(0),
  CANCELLED(1);

  companion object {
    fun ofRaw(raw: Int): PlatformCameraAnimationResult? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/** Причина перемещения камеры. */
enum class PlatformCameraMovingReason(val raw: Int) {
  GESTURE(0),
  API(1),
  FOLLOW_MODE(2),
  UNKNOWN(3);

  companion object {
    fun ofRaw(raw: Int): PlatformCameraMovingReason? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/** Фаза перемещения камеры. */
enum class PlatformCameraMovingPhase(val raw: Int) {
  STARTED(0),
  MOVING(1),
  SINGLE_COMPLETED(2),
  ALL_COMPLETED(3),
  CANCELLED(4);

  companion object {
    fun ofRaw(raw: Int): PlatformCameraMovingPhase? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/** Тип события карты. */
enum class PlatformMapEventType(val raw: Int) {
  MAP_SHOWN(0),
  TAP(1),
  LONG_TAP(2),
  MARKER_TAP(3),
  CAMERA_MOVE(4),
  STYLE_APPLIED(5),
  MODE_CHANGED(6),
  LOW_MEMORY(7),
  ERROR(8);

  companion object {
    fun ofRaw(raw: Int): PlatformMapEventType? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class PlatformLatLon (
  val latitude: Double,
  val longitude: Double
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): PlatformLatLon {
      val latitude = pigeonVar_list[0] as Double
      val longitude = pigeonVar_list[1] as Double
      return PlatformLatLon(latitude, longitude)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      latitude,
      longitude,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is PlatformLatLon) {
      return false
    }
    if (this === other) {
      return true
    }
    return MessagesPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/** Generated class from Pigeon that represents data sent in messages. */
data class PlatformLatLonBounds (
  val southwest: PlatformLatLon,
  val northeast: PlatformLatLon
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): PlatformLatLonBounds {
      val southwest = pigeonVar_list[0] as PlatformLatLon
      val northeast = pigeonVar_list[1] as PlatformLatLon
      return PlatformLatLonBounds(southwest, northeast)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      southwest,
      northeast,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is PlatformLatLonBounds) {
      return false
    }
    if (this === other) {
      return true
    }
    return MessagesPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/** Generated class from Pigeon that represents data sent in messages. */
data class PlatformScreenPoint (
  val x: Double,
  val y: Double
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): PlatformScreenPoint {
      val x = pigeonVar_list[0] as Double
      val y = pigeonVar_list[1] as Double
      return PlatformScreenPoint(x, y)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      x,
      y,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is PlatformScreenPoint) {
      return false
    }
    if (this === other) {
      return true
    }
    return MessagesPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/** Generated class from Pigeon that represents data sent in messages. */
data class PlatformEdgeInsets (
  val left: Double,
  val top: Double,
  val right: Double,
  val bottom: Double
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): PlatformEdgeInsets {
      val left = pigeonVar_list[0] as Double
      val top = pigeonVar_list[1] as Double
      val right = pigeonVar_list[2] as Double
      val bottom = pigeonVar_list[3] as Double
      return PlatformEdgeInsets(left, top, right, bottom)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      left,
      top,
      right,
      bottom,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is PlatformEdgeInsets) {
      return false
    }
    if (this === other) {
      return true
    }
    return MessagesPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/** Generated class from Pigeon that represents data sent in messages. */
data class PlatformCameraPosition (
  val target: PlatformLatLon,
  val zoom: Double,
  val bearing: Double,
  val pitch: Double
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): PlatformCameraPosition {
      val target = pigeonVar_list[0] as PlatformLatLon
      val zoom = pigeonVar_list[1] as Double
      val bearing = pigeonVar_list[2] as Double
      val pitch = pigeonVar_list[3] as Double
      return PlatformCameraPosition(target, zoom, bearing, pitch)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      target,
      zoom,
      bearing,
      pitch,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is PlatformCameraPosition) {
      return false
    }
    if (this === other) {
      return true
    }
    return MessagesPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/** Generated class from Pigeon that represents data sent in messages. */
data class PlatformCameraOptions (
  val zoom: Double? = null,
  val bearing: Double? = null,
  val pitch: Double? = null,
  val padding: PlatformEdgeInsets? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): PlatformCameraOptions {
      val zoom = pigeonVar_list[0] as Double?
      val bearing = pigeonVar_list[1] as Double?
      val pitch = pigeonVar_list[2] as Double?
      val padding = pigeonVar_list[3] as PlatformEdgeInsets?
      return PlatformCameraOptions(zoom, bearing, pitch, padding)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      zoom,
      bearing,
      pitch,
      padding,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is PlatformCameraOptions) {
      return false
    }
    if (this === other) {
      return true
    }
    return MessagesPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/** Generated class from Pigeon that represents data sent in messages. */
data class PlatformAnimationOptions (
  val durationMillis: Long,
  val easing: PlatformAnimationEasing,
  val durationMode: PlatformAnimationDurationMode
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): PlatformAnimationOptions {
      val durationMillis = pigeonVar_list[0] as Long
      val easing = pigeonVar_list[1] as PlatformAnimationEasing
      val durationMode = pigeonVar_list[2] as PlatformAnimationDurationMode
      return PlatformAnimationOptions(durationMillis, easing, durationMode)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      durationMillis,
      easing,
      durationMode,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is PlatformAnimationOptions) {
      return false
    }
    if (this === other) {
      return true
    }
    return MessagesPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/**
 * Стиль карты: `kind` определяет, что лежит в остальных полях.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class PlatformStyle (
  val kind: PlatformStyleKind,
  val predefined: PlatformPredefinedStyle? = null,
  val json: String? = null,
  val url: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): PlatformStyle {
      val kind = pigeonVar_list[0] as PlatformStyleKind
      val predefined = pigeonVar_list[1] as PlatformPredefinedStyle?
      val json = pigeonVar_list[2] as String?
      val url = pigeonVar_list[3] as String?
      return PlatformStyle(kind, predefined, json, url)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      kind,
      predefined,
      json,
      url,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is PlatformStyle) {
      return false
    }
    if (this === other) {
      return true
    }
    return MessagesPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/**
 * Настройки карты. Незаданные поля означают «не менять».
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class PlatformMapConfiguration (
  val style: PlatformStyle? = null,
  val compassEnabled: Boolean? = null,
  val zoomButtonsEnabled: Boolean? = null,
  val currentLocationButtonEnabled: Boolean? = null,
  val scrollGesturesEnabled: Boolean? = null,
  val zoomGesturesEnabled: Boolean? = null,
  val rotateGesturesEnabled: Boolean? = null,
  val logoAlignment: PlatformLogoAlignment? = null,
  val logoInsets: PlatformEdgeInsets? = null,
  val logoIgnoresSafeArea: Boolean? = null,
  val padding: PlatformEdgeInsets? = null,
  val featuresSelectionMode: PlatformFeaturesSelectionMode? = null,
  val minZoom: Double? = null,
  val maxZoom: Double? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): PlatformMapConfiguration {
      val style = pigeonVar_list[0] as PlatformStyle?
      val compassEnabled = pigeonVar_list[1] as Boolean?
      val zoomButtonsEnabled = pigeonVar_list[2] as Boolean?
      val currentLocationButtonEnabled = pigeonVar_list[3] as Boolean?
      val scrollGesturesEnabled = pigeonVar_list[4] as Boolean?
      val zoomGesturesEnabled = pigeonVar_list[5] as Boolean?
      val rotateGesturesEnabled = pigeonVar_list[6] as Boolean?
      val logoAlignment = pigeonVar_list[7] as PlatformLogoAlignment?
      val logoInsets = pigeonVar_list[8] as PlatformEdgeInsets?
      val logoIgnoresSafeArea = pigeonVar_list[9] as Boolean?
      val padding = pigeonVar_list[10] as PlatformEdgeInsets?
      val featuresSelectionMode = pigeonVar_list[11] as PlatformFeaturesSelectionMode?
      val minZoom = pigeonVar_list[12] as Double?
      val maxZoom = pigeonVar_list[13] as Double?
      return PlatformMapConfiguration(style, compassEnabled, zoomButtonsEnabled, currentLocationButtonEnabled, scrollGesturesEnabled, zoomGesturesEnabled, rotateGesturesEnabled, logoAlignment, logoInsets, logoIgnoresSafeArea, padding, featuresSelectionMode, minZoom, maxZoom)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      style,
      compassEnabled,
      zoomButtonsEnabled,
      currentLocationButtonEnabled,
      scrollGesturesEnabled,
      zoomGesturesEnabled,
      rotateGesturesEnabled,
      logoAlignment,
      logoInsets,
      logoIgnoresSafeArea,
      padding,
      featuresSelectionMode,
      minZoom,
      maxZoom,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is PlatformMapConfiguration) {
      return false
    }
    if (this === other) {
      return true
    }
    return MessagesPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/** Generated class from Pigeon that represents data sent in messages. */
data class PlatformMapCreationParams (
  val initialCameraPosition: PlatformCameraPosition,
  val configuration: PlatformMapConfiguration,
  val platformViewType: PlatformViewType
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): PlatformMapCreationParams {
      val initialCameraPosition = pigeonVar_list[0] as PlatformCameraPosition
      val configuration = pigeonVar_list[1] as PlatformMapConfiguration
      val platformViewType = pigeonVar_list[2] as PlatformViewType
      return PlatformMapCreationParams(initialCameraPosition, configuration, platformViewType)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      initialCameraPosition,
      configuration,
      platformViewType,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is PlatformMapCreationParams) {
      return false
    }
    if (this === other) {
      return true
    }
    return MessagesPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/** Generated class from Pigeon that represents data sent in messages. */
data class PlatformMarker (
  val markerId: String,
  val position: PlatformLatLon,
  val imageId: String,
  val alignment: PlatformMarkerAlignment,
  val zIndex: Long,
  val visible: Boolean
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): PlatformMarker {
      val markerId = pigeonVar_list[0] as String
      val position = pigeonVar_list[1] as PlatformLatLon
      val imageId = pigeonVar_list[2] as String
      val alignment = pigeonVar_list[3] as PlatformMarkerAlignment
      val zIndex = pigeonVar_list[4] as Long
      val visible = pigeonVar_list[5] as Boolean
      return PlatformMarker(markerId, position, imageId, alignment, zIndex, visible)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      markerId,
      position,
      imageId,
      alignment,
      zIndex,
      visible,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is PlatformMarker) {
      return false
    }
    if (this === other) {
      return true
    }
    return MessagesPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/**
 * Дельта набора маркеров: только то, что изменилось.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class PlatformMarkerUpdates (
  val toAdd: List<PlatformMarker>,
  val toChange: List<PlatformMarker>,
  val idsToRemove: List<String>
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): PlatformMarkerUpdates {
      val toAdd = pigeonVar_list[0] as List<PlatformMarker>
      val toChange = pigeonVar_list[1] as List<PlatformMarker>
      val idsToRemove = pigeonVar_list[2] as List<String>
      return PlatformMarkerUpdates(toAdd, toChange, idsToRemove)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      toAdd,
      toChange,
      idsToRemove,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is PlatformMarkerUpdates) {
      return false
    }
    if (this === other) {
      return true
    }
    return MessagesPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/**
 * Событие карты. Набор заполненных полей определяется полем `type`.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class PlatformMapEvent (
  val type: PlatformMapEventType,
  val position: PlatformLatLon? = null,
  val screenPoint: PlatformScreenPoint? = null,
  val markerId: String? = null,
  val cameraPosition: PlatformCameraPosition? = null,
  val cameraMovingReason: PlatformCameraMovingReason? = null,
  val cameraMovingPhase: PlatformCameraMovingPhase? = null,
  val mode: PlatformMapMode? = null,
  val errorCode: String? = null,
  val errorMessage: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): PlatformMapEvent {
      val type = pigeonVar_list[0] as PlatformMapEventType
      val position = pigeonVar_list[1] as PlatformLatLon?
      val screenPoint = pigeonVar_list[2] as PlatformScreenPoint?
      val markerId = pigeonVar_list[3] as String?
      val cameraPosition = pigeonVar_list[4] as PlatformCameraPosition?
      val cameraMovingReason = pigeonVar_list[5] as PlatformCameraMovingReason?
      val cameraMovingPhase = pigeonVar_list[6] as PlatformCameraMovingPhase?
      val mode = pigeonVar_list[7] as PlatformMapMode?
      val errorCode = pigeonVar_list[8] as String?
      val errorMessage = pigeonVar_list[9] as String?
      return PlatformMapEvent(type, position, screenPoint, markerId, cameraPosition, cameraMovingReason, cameraMovingPhase, mode, errorCode, errorMessage)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      type,
      position,
      screenPoint,
      markerId,
      cameraPosition,
      cameraMovingReason,
      cameraMovingPhase,
      mode,
      errorCode,
      errorMessage,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is PlatformMapEvent) {
      return false
    }
    if (this === other) {
      return true
    }
    return MessagesPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}
private open class MessagesPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          PlatformPredefinedStyle.ofRaw(it.toInt())
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          PlatformStyleKind.ofRaw(it.toInt())
        }
      }
      131.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          PlatformMapMode.ofRaw(it.toInt())
        }
      }
      132.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          PlatformLogoAlignment.ofRaw(it.toInt())
        }
      }
      133.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          PlatformMarkerAlignment.ofRaw(it.toInt())
        }
      }
      134.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          PlatformAnimationEasing.ofRaw(it.toInt())
        }
      }
      135.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          PlatformAnimationDurationMode.ofRaw(it.toInt())
        }
      }
      136.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          PlatformFeaturesSelectionMode.ofRaw(it.toInt())
        }
      }
      137.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          PlatformViewType.ofRaw(it.toInt())
        }
      }
      138.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          PlatformCameraAnimationResult.ofRaw(it.toInt())
        }
      }
      139.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          PlatformCameraMovingReason.ofRaw(it.toInt())
        }
      }
      140.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          PlatformCameraMovingPhase.ofRaw(it.toInt())
        }
      }
      141.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          PlatformMapEventType.ofRaw(it.toInt())
        }
      }
      142.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          PlatformLatLon.fromList(it)
        }
      }
      143.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          PlatformLatLonBounds.fromList(it)
        }
      }
      144.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          PlatformScreenPoint.fromList(it)
        }
      }
      145.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          PlatformEdgeInsets.fromList(it)
        }
      }
      146.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          PlatformCameraPosition.fromList(it)
        }
      }
      147.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          PlatformCameraOptions.fromList(it)
        }
      }
      148.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          PlatformAnimationOptions.fromList(it)
        }
      }
      149.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          PlatformStyle.fromList(it)
        }
      }
      150.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          PlatformMapConfiguration.fromList(it)
        }
      }
      151.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          PlatformMapCreationParams.fromList(it)
        }
      }
      152.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          PlatformMarker.fromList(it)
        }
      }
      153.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          PlatformMarkerUpdates.fromList(it)
        }
      }
      154.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          PlatformMapEvent.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is PlatformPredefinedStyle -> {
        stream.write(129)
        writeValue(stream, value.raw)
      }
      is PlatformStyleKind -> {
        stream.write(130)
        writeValue(stream, value.raw)
      }
      is PlatformMapMode -> {
        stream.write(131)
        writeValue(stream, value.raw)
      }
      is PlatformLogoAlignment -> {
        stream.write(132)
        writeValue(stream, value.raw)
      }
      is PlatformMarkerAlignment -> {
        stream.write(133)
        writeValue(stream, value.raw)
      }
      is PlatformAnimationEasing -> {
        stream.write(134)
        writeValue(stream, value.raw)
      }
      is PlatformAnimationDurationMode -> {
        stream.write(135)
        writeValue(stream, value.raw)
      }
      is PlatformFeaturesSelectionMode -> {
        stream.write(136)
        writeValue(stream, value.raw)
      }
      is PlatformViewType -> {
        stream.write(137)
        writeValue(stream, value.raw)
      }
      is PlatformCameraAnimationResult -> {
        stream.write(138)
        writeValue(stream, value.raw)
      }
      is PlatformCameraMovingReason -> {
        stream.write(139)
        writeValue(stream, value.raw)
      }
      is PlatformCameraMovingPhase -> {
        stream.write(140)
        writeValue(stream, value.raw)
      }
      is PlatformMapEventType -> {
        stream.write(141)
        writeValue(stream, value.raw)
      }
      is PlatformLatLon -> {
        stream.write(142)
        writeValue(stream, value.toList())
      }
      is PlatformLatLonBounds -> {
        stream.write(143)
        writeValue(stream, value.toList())
      }
      is PlatformScreenPoint -> {
        stream.write(144)
        writeValue(stream, value.toList())
      }
      is PlatformEdgeInsets -> {
        stream.write(145)
        writeValue(stream, value.toList())
      }
      is PlatformCameraPosition -> {
        stream.write(146)
        writeValue(stream, value.toList())
      }
      is PlatformCameraOptions -> {
        stream.write(147)
        writeValue(stream, value.toList())
      }
      is PlatformAnimationOptions -> {
        stream.write(148)
        writeValue(stream, value.toList())
      }
      is PlatformStyle -> {
        stream.write(149)
        writeValue(stream, value.toList())
      }
      is PlatformMapConfiguration -> {
        stream.write(150)
        writeValue(stream, value.toList())
      }
      is PlatformMapCreationParams -> {
        stream.write(151)
        writeValue(stream, value.toList())
      }
      is PlatformMarker -> {
        stream.write(152)
        writeValue(stream, value.toList())
      }
      is PlatformMarkerUpdates -> {
        stream.write(153)
        writeValue(stream, value.toList())
      }
      is PlatformMapEvent -> {
        stream.write(154)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}


/**
 * Разовая настройка SDK на процесс: ключ доступа и параметры сети.
 *
 * Generated interface from Pigeon that represents a handler of messages from Flutter.
 */
interface VkMapsInitializerApi {
  /** Настраивает SDK. Повторный вызов с теми же параметрами ничего не делает. */
  fun setup(apiKey: String, baseUrl: String?, locale: String?, callback: (Result<Boolean>) -> Unit)
  /** Настроен ли SDK. */
  fun isInitialized(): Boolean

  companion object {
    /** The codec used by VkMapsInitializerApi. */
    val codec: MessageCodec<Any?> by lazy {
      MessagesPigeonCodec()
    }
    /** Sets up an instance of `VkMapsInitializerApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: VkMapsInitializerApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.vk_maps_mapkit_platform_interface.VkMapsInitializerApi.setup$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val apiKeyArg = args[0] as String
            val baseUrlArg = args[1] as String?
            val localeArg = args[2] as String?
            api.setup(apiKeyArg, baseUrlArg, localeArg) { result: Result<Boolean> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(MessagesPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(MessagesPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.vk_maps_mapkit_platform_interface.VkMapsInitializerApi.isInitialized$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.isInitialized())
            } catch (exception: Throwable) {
              MessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
/**
 * Управление конкретной картой. Первый аргумент — идентификатор
 * platform view, потому что карт в приложении может быть несколько.
 *
 * Generated interface from Pigeon that represents a handler of messages from Flutter.
 */
interface VkMapsHostApi {
  /** Применяет настройки карты. Передавать только изменившиеся поля. */
  fun updateConfiguration(viewId: Long, configuration: PlatformMapConfiguration)
  /** Применяет дельту набора маркеров. */
  fun updateMarkers(viewId: Long, updates: PlatformMarkerUpdates)
  /** Перемещает камеру. Пустые `animation` означают мгновенное перемещение. */
  fun moveCamera(viewId: Long, target: PlatformLatLon?, options: PlatformCameraOptions?, animation: PlatformAnimationOptions?, callback: (Result<PlatformCameraAnimationResult>) -> Unit)
  /** Вписывает область в карту. */
  fun fitBounds(viewId: Long, bounds: PlatformLatLonBounds, padding: PlatformEdgeInsets, animation: PlatformAnimationOptions?, callback: (Result<PlatformCameraAnimationResult>) -> Unit)
  /** Текущее положение камеры. */
  fun getCameraPosition(viewId: Long): PlatformCameraPosition
  /** Границы видимой области. */
  fun getVisibleBounds(viewId: Long): PlatformLatLonBounds
  /** Координата по точке на экране. */
  fun coordinateForScreenPoint(viewId: Long, point: PlatformScreenPoint): PlatformLatLon?
  /** Точка на экране по координате. */
  fun screenPointForCoordinate(viewId: Long, coordinate: PlatformLatLon): PlatformScreenPoint?
  /** Текущий режим следования. */
  fun getMode(viewId: Long): PlatformMapMode
  /** Устанавливает режим следования. */
  fun setMode(viewId: Long, mode: PlatformMapMode)
  /** Задаёт положение индикатора пользователя. */
  fun setUserLocation(viewId: Long, coordinates: PlatformLatLon?, bearing: Double?, accuracy: Double?, visible: Boolean)
  /**
   * Добавляет изображение в стиль карты, чтобы на него могли ссылаться
   * маркеры.
   */
  fun addStyleImage(viewId: Long, imageId: String, pngBytes: ByteArray, scale: Double, callback: (Result<Unit>) -> Unit)
  /** Убирает изображение из стиля. */
  fun removeStyleImage(viewId: Long, imageId: String)
  /** Освобождает ресурсы карты. */
  fun dispose(viewId: Long)

  companion object {
    /** The codec used by VkMapsHostApi. */
    val codec: MessageCodec<Any?> by lazy {
      MessagesPigeonCodec()
    }
    /** Sets up an instance of `VkMapsHostApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: VkMapsHostApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.vk_maps_mapkit_platform_interface.VkMapsHostApi.updateConfiguration$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val viewIdArg = args[0] as Long
            val configurationArg = args[1] as PlatformMapConfiguration
            val wrapped: List<Any?> = try {
              api.updateConfiguration(viewIdArg, configurationArg)
              listOf(null)
            } catch (exception: Throwable) {
              MessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.vk_maps_mapkit_platform_interface.VkMapsHostApi.updateMarkers$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val viewIdArg = args[0] as Long
            val updatesArg = args[1] as PlatformMarkerUpdates
            val wrapped: List<Any?> = try {
              api.updateMarkers(viewIdArg, updatesArg)
              listOf(null)
            } catch (exception: Throwable) {
              MessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.vk_maps_mapkit_platform_interface.VkMapsHostApi.moveCamera$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val viewIdArg = args[0] as Long
            val targetArg = args[1] as PlatformLatLon?
            val optionsArg = args[2] as PlatformCameraOptions?
            val animationArg = args[3] as PlatformAnimationOptions?
            api.moveCamera(viewIdArg, targetArg, optionsArg, animationArg) { result: Result<PlatformCameraAnimationResult> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(MessagesPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(MessagesPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.vk_maps_mapkit_platform_interface.VkMapsHostApi.fitBounds$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val viewIdArg = args[0] as Long
            val boundsArg = args[1] as PlatformLatLonBounds
            val paddingArg = args[2] as PlatformEdgeInsets
            val animationArg = args[3] as PlatformAnimationOptions?
            api.fitBounds(viewIdArg, boundsArg, paddingArg, animationArg) { result: Result<PlatformCameraAnimationResult> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(MessagesPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(MessagesPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.vk_maps_mapkit_platform_interface.VkMapsHostApi.getCameraPosition$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val viewIdArg = args[0] as Long
            val wrapped: List<Any?> = try {
              listOf(api.getCameraPosition(viewIdArg))
            } catch (exception: Throwable) {
              MessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.vk_maps_mapkit_platform_interface.VkMapsHostApi.getVisibleBounds$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val viewIdArg = args[0] as Long
            val wrapped: List<Any?> = try {
              listOf(api.getVisibleBounds(viewIdArg))
            } catch (exception: Throwable) {
              MessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.vk_maps_mapkit_platform_interface.VkMapsHostApi.coordinateForScreenPoint$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val viewIdArg = args[0] as Long
            val pointArg = args[1] as PlatformScreenPoint
            val wrapped: List<Any?> = try {
              listOf(api.coordinateForScreenPoint(viewIdArg, pointArg))
            } catch (exception: Throwable) {
              MessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.vk_maps_mapkit_platform_interface.VkMapsHostApi.screenPointForCoordinate$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val viewIdArg = args[0] as Long
            val coordinateArg = args[1] as PlatformLatLon
            val wrapped: List<Any?> = try {
              listOf(api.screenPointForCoordinate(viewIdArg, coordinateArg))
            } catch (exception: Throwable) {
              MessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.vk_maps_mapkit_platform_interface.VkMapsHostApi.getMode$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val viewIdArg = args[0] as Long
            val wrapped: List<Any?> = try {
              listOf(api.getMode(viewIdArg))
            } catch (exception: Throwable) {
              MessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.vk_maps_mapkit_platform_interface.VkMapsHostApi.setMode$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val viewIdArg = args[0] as Long
            val modeArg = args[1] as PlatformMapMode
            val wrapped: List<Any?> = try {
              api.setMode(viewIdArg, modeArg)
              listOf(null)
            } catch (exception: Throwable) {
              MessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.vk_maps_mapkit_platform_interface.VkMapsHostApi.setUserLocation$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val viewIdArg = args[0] as Long
            val coordinatesArg = args[1] as PlatformLatLon?
            val bearingArg = args[2] as Double?
            val accuracyArg = args[3] as Double?
            val visibleArg = args[4] as Boolean
            val wrapped: List<Any?> = try {
              api.setUserLocation(viewIdArg, coordinatesArg, bearingArg, accuracyArg, visibleArg)
              listOf(null)
            } catch (exception: Throwable) {
              MessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.vk_maps_mapkit_platform_interface.VkMapsHostApi.addStyleImage$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val viewIdArg = args[0] as Long
            val imageIdArg = args[1] as String
            val pngBytesArg = args[2] as ByteArray
            val scaleArg = args[3] as Double
            api.addStyleImage(viewIdArg, imageIdArg, pngBytesArg, scaleArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(MessagesPigeonUtils.wrapError(error))
              } else {
                reply.reply(MessagesPigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.vk_maps_mapkit_platform_interface.VkMapsHostApi.removeStyleImage$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val viewIdArg = args[0] as Long
            val imageIdArg = args[1] as String
            val wrapped: List<Any?> = try {
              api.removeStyleImage(viewIdArg, imageIdArg)
              listOf(null)
            } catch (exception: Throwable) {
              MessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.vk_maps_mapkit_platform_interface.VkMapsHostApi.dispose$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val viewIdArg = args[0] as Long
            val wrapped: List<Any?> = try {
              api.dispose(viewIdArg)
              listOf(null)
            } catch (exception: Throwable) {
              MessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
/**
 * События карты, которые натив шлёт во Flutter.
 *
 * Generated class from Pigeon that represents Flutter messages that can be called from Kotlin.
 */
class VkMapsFlutterApi(private val binaryMessenger: BinaryMessenger, private val messageChannelSuffix: String = "") {
  companion object {
    /** The codec used by VkMapsFlutterApi. */
    val codec: MessageCodec<Any?> by lazy {
      MessagesPigeonCodec()
    }
  }
  /** Событие карты [viewId]. */
  fun onEvent(viewIdArg: Long, eventArg: PlatformMapEvent, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.vk_maps_mapkit_platform_interface.VkMapsFlutterApi.onEvent$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(viewIdArg, eventArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(MessagesPigeonUtils.createConnectionError(channelName)))
      } 
    }
  }
}
